<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Open;

use App\Helpers\AuthUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Http\Controllers\Core\PublicController;
use App\Models\Assets\Vehicle;
use App\Models\Tour\Baggage;
use App\Models\Cms\Article;
use App\Models\Core\Mongo\User;
use http\Env\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class HomeController extends PublicController
{
    public function __construct()
    {
        parent::__construct();

        $this->model = new Article();
    }

    public function getPage($slug)
    {
        $this->title = 'Dashboard';


        $article = Article::where('slug','=', $slug)->first();
        $this->data = $article->toArray();
        $this->title = $article->title;
        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);

        $this->nav_section = 'users';
        $this->yml_file = 'fields';
        $this->res_path = 'views/lumbungku/admin/fieldreport';

        $this->template_var = [ 'hasSideNav'=>false ];

        $this->data_url = 'admin/fieldreport';

        $this->table_view = env('ADMIN_DASHBOARD_VIEW', 'tour.admin.dashboard');

        $this->form_view = 'tour.open.page.page';


        // return view('tour.open.page.page')->with('article', $article);
        return parent::formGenerator();
    }

    public function getIndex()
    {
        $this->title = 'Dashboard';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);

        $this->nav_section = 'users';
        $this->yml_file = 'fields';

        $this->template_var = [ 'hasSideNav'=>false ];

        $this->can_add = true;

        $this->data_url = 'admin/fieldreport';

        $this->table_view = env('ADMIN_DASHBOARD_VIEW', 'trips.dashboard');

        return parent::getIndex();
    }

    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        return parent::beforeSave($data);
    }

    protected function rowPostProcess($row)
    {
        /* modify or add new fields */
        //$row['linkConsult'] = url('clinic/patient/km/'.$row['_id']);
        //$row['linkOp'] = url('clinic/patient/op/'.$row['_id']);

        return parent::rowPostProcess($row);
    }

    /*  Example External data interceptopr
     *
     *
     * */

    /*  Example API Proxy
     *
     *
     * */
    public function getBaggageData($id)
    {
//        $client = new Client();
//        $result = $client->get(env('KMN_DATA_URL').'/'.$id, [
//            'form_params' => [
//                'sample-form-data' => 'value'
//            ]
//        ]);
//
//        return response($result->getBody())
//            ->withHeaders([
//                'Content-Type' => 'application/json'
//            ]);
//

        $handle = Str::random(12);
        $result = ['result'=>'OK', 'data'=>['handle'=>$handle]];
        return response()->json($result);

    }

    public function getData($id, $additional_data = null)
    {
        $handle = Str::random(12);
        $result = ['result'=>'OK', 'data'=>['handle'=>$handle]];
        return response()->json($result);
        //return parent::getData($id, $additional_data); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {
        $handle = Str::random(12);
        $code = Str::random(12);
        $result = ['result'=>'OK', 'data'=>['handle'=>$handle,'code'=>$code]];
        return response()->json($result);
        return parent::getParam(); // TODO: Change the autogenerated stub
    }


    /* Custom form sample route method
     * requires manual route setting
     * */
    public function getReg(){

//        $this->nav_section = 'users';
        $this->yml_file = 'reg';
        $this->res_path = 'views/home';
        $this->nav_file = 'nav';
        $this->nav_path = env('APP_NAV_PATH');
        $this->yml_layout_file = 'op_layout';
        $this->logo = env('APP_LOGO');

        /* Injected model data, merged with vue data model as well
         * */

        $this->title = 'Baggage Registration';

        $this->show_title = false;

        $this->item_data_url = 'tour/baggage/param';

        $this->add_url = 'clinic/konsul/add';

        $this->update_url = 'clinic/konsul/relay';

        $this->autosave_url = 'clinic/konsul/autosave';

        $this->item_id = '';

        $this->has_tab = false;

        $this->form_view = 'form.flatgridpage';

        $this->form_mode = 'edit';

        $this->can_autosave = false;

        $this->can_add = true;

        $this->can_lock = true;

        $this->grid = [
            ['col'=>[5,7]],
        ];

        $uiOptions = [

        ];

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $this->aux_data = array_merge( $uiOptions ,$formOptions);

//        $this->js_load_transform = 'clinic.patient.konsul_js_load_transform';
//
//        $this->js_post_transform = 'clinic.patient.konsul_js_post_transform';
//
//        $this->js_tab_change = 'clinic.patient.konsul_js_tab_change';
//
//        $this->js_pop_open = 'clinic.patient.konsul_js_pop_open';

//        $this->aux_data['patientData'] = '{}';

        return parent::formGenerator();
    }

    public function getCheck(){

//        $this->nav_section = 'users';
        $this->yml_file = 'check';
        $this->res_path = 'views/tour/baggage';
        $this->nav_file = 'nav';
        $this->nav_path = env('APP_NAV_PATH');
        $this->yml_layout_file = 'op_layout';
        $this->logo = env('APP_LOGO');

        /* Injected model data, merged with vue data model as well
         * */

        $this->title = 'Baggage Check';

        $this->show_title = false;

        $this->item_data_url = 'tour/baggage/param';

        $this->add_url = 'clinic/konsul/add';

        $this->update_url = 'clinic/konsul/relay';

        $this->autosave_url = 'clinic/konsul/autosave';

        $this->item_id = '';

        $this->has_tab = false;

        $this->form_view = 'form.flatgridpage';

        $this->form_mode = 'edit';

        $this->can_autosave = false;

        $this->can_add = true;

        $this->can_lock = true;

        $this->grid = [
            ['col'=>[5,7]],
        ];

        $baggageDataDefaultObject = [
            'name'=>'',
            'idNumber'=>'',
            'nationality'=>'',
            'picture'=>url('images/default_photo.jpg')
        ];

        $baggageDataTemplate = '`'. file_get_contents( resource_path('views/tour/baggage/baggage_info.html')) .'`';
        $uiOptions = [
            'baggageDataTemplate'=>$baggageDataTemplate,
            'baggageDataDefaultObject'=>$baggageDataDefaultObject
        ];

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $this->aux_data = array_merge( $uiOptions ,$formOptions);

//        $this->js_load_transform = 'clinic.patient.konsul_js_load_transform';
//
//        $this->js_post_transform = 'clinic.patient.konsul_js_post_transform';
//
//        $this->js_tab_change = 'clinic.patient.konsul_js_tab_change';
//
//        $this->js_pop_open = 'clinic.patient.konsul_js_pop_open';

//        $this->aux_data['patientData'] = '{}';

        return parent::formGenerator();
    }

    public function getQuery(Request $request){
        $q = $request->get('q');

        $res = Vehicle::where('code','=', trim($q))->first();

        if($res){
            $data = $res->toArray();
        }else{
            $data = [
                'name'=>'Johhny Ive',
                'idNumber'=>'X5653353',
                'nationality'=>'British',
                'picture'=>url('images/default_photo.jpg')
            ];
        }


        return response()->json(['result'=>'OK', 'data'=>$data] );
    }

}
