<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Workflow\Approval;

use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Helpers\Injector;
use App\Http\Controllers\Core\AdminController;
use App\Models\Workflow\ApprovalRequest;
use App\Models\Workflow\ApprovalLog;
use App\Models\Core\Mongo\User;
use App\Models\Workflow\Approver;
use App\Models\Workflow\DefaultApprover;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class DefaultApproverController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'views/workflow/defaultapprover';
        $this->yml_file = 'fields';


        $this->entity = 'Default Approver';

        $this->auth_entity = 'workflow-default-approver';
        $this->controller_base = 'workflow/approval/default-approver';
        $this->view_base = 'workflow.approval.defaultapprover';

        $this->model = new DefaultApprover();
    }

    /**
     * @hideFromAPIDocumentation
     * @return mixed
     */
    public function getIndex()
    {
        $this->title = 'Default Approvers';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);

        $this->runUrlSet();
        $this->runAcl();
        $this->runViewSet();

        $this->logo = env('APP_LOGO');

        $this->show_title = true;

        $this->viewer_layout = 'workflow.defaultapprover.formlayout';

        /* Use custom form layout
        *  default to form.flatgrid
        *  change form_view & view_layout
        */
        // use custom form
        //$this->form_view = 'form.custom';
        // or use html template for mote detailed control without having to fiddle with YML
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'workflow.defaultapprover.formlayout';
        $this->form_dialog_size = 'md';


        /* slot view for cell formating
        */
        //$this->table_slot_view = 'loyalty.reference/productcategory.tableslot';
         // use injector to provide options for simpleselect / localselect
         $uiOptions =[];
         $uiOptions = Injector::setModel( ApprovalLog::orderBy('categoryCode') ) // gunakan model sebagai input, set query disini
         ->toModelArray() // akan running query dan menghasilkan array object
         ->toOptions('categoryName', 'categoryCode', true) // jadikan option untuk select
         ->injectOption('category', $uiOptions); // inject ke uioptions, gunakan nama field biasa tanpa suffix, suffix & prefix akan dihandle di fungsi injectOption

         $uiOptions = Injector::setModel( Approver::orderBy('sectionCode') ) // gunakan model sebagai input, set query disini
         ->toModelArray() // akan running query dan menghasilkan array object
         ->toOptions('sectionName', 'sectionCode', true) // jadikan option untuk select
         ->injectOption('section', $uiOptions); // inject ke uioptions, gunakan nama field biasa tanpa suffix, suffix & prefix akan dihandle di fungsi injectOption

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();
        $this->aux_data = array_merge( $uiOptions ,$formOptions);

        $this->view_title_fields = 'this.title';

        //$this->table_component = 'ant-vue-table';

        return parent::getIndex();
    }

    /**
     * @hideFromAPIDocumentation
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function postIndex(Request $request)
    {
        //$this->defOrderField = 'IODate';
        //$this->defOrderDir = 'desc';
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }


    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        $data['version'] = config('dbversions.product_categories');
        return parent::beforeSave($data);
    }

    protected function rowPostProcess($row)
    {
        /* modify or add new fields */
        //$row['linkConsult'] = url('clinic/patient/km/'.$row['_id']);
        //$row['linkOp'] = url('clinic/patient/op/'.$row['_id']);

        return parent::rowPostProcess($row);
    }

    // Transform fields before commited into the database collection ( xls import )
    public function beforeImportCommit($data)
    {
        //example : transform imported data to datetime field
        // $data['IODate'] = ImportUtil::excelDateToNormal($data['IODate']);
        // $data['DocDate'] = ImportUtil::excelDateToNormal($data['DocDate']);
        // $data['RetDate'] = ImportUtil::excelDateToNormal($data['RetDate']);
        // $data['DispDate'] = ImportUtil::excelDateToNormal($data['DispDate']);
        $data['version'] = config('dbversions.product_categories');
        return parent::beforeImportCommit($data); // TODO: Change the autogenerated stub
    }


    public function beforeUpdate($id, $data)
    {
        $data['version'] = config('dbversions.product_categories');
        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }
}
