<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Cms;

use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Cms\Section;
use Illuminate\Http\Request;

class SectionController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/cms';
        $this->yml_file = 'section_controller';

        $this->entity = 'Section';
        $this->view_base = 'cms.section';
        $this->auth_entity = 'cms-section';
        $this->controller_base = 'cms/section';

        $this->clone_name_field = 'sectionName';

        $this->model = new Section();
    }

    /**
     * @hideFromAPIDocumentation
     * @return mixed
     */
    public function getIndex()
    {
        $this->title = 'Section';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);

        $this->template_var = [ 'hasSideNav'=>true ];


        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->import_commit_url = 'cms/section/commit';

        $this->logo = env('APP_LOGO');

        $this->show_title = true;

        $this->viewer_layout = 'cms.section.formlayout';

        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'cms.section.formlayout';
        $this->form_dialog_size = 'md';
        $this->viewer_dialog_size = 'md';

        $this->can_approve = false;
        $this->can_request_approval = false;
        $this->can_revise = false;

        $uiOptions =[];
        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();
        $this->aux_data = array_merge( $uiOptions ,$formOptions);

        return parent::getIndex();
    }

    /**
     * @hideFromAPIDocumentation
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function postIndex(Request $request)
    {
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }


    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        $data['version'] = config('dbversions.product_categories');
        return parent::beforeSave($data);
    }

    protected function rowPostProcess($row)
    {
        return parent::rowPostProcess($row);
    }

    // Transform fields before commited into the database collection ( xls import )
    public function beforeImportCommit($data)
    {
        return parent::beforeImportCommit($data); // TODO: Change the autogenerated stub
    }


    public function beforeUpdate($id, $data)
    {
        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }
}
