<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Dwf;

use App\Helpers\App\DwfUtil;
use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Core\Mongo\User;
use App\Models\Dwf\Admin\ArchiveType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ArchiveTypeController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/dwf';

        $this->yml_file = 'archivetype_controller';

        $this->entity = 'Jenis Arsip';

        $this->auth_entity = 'archive-type';

        $this->controller_base = 'dwf/admin/archive-type';

        $this->view_base = 'dwf.archivetype';

        $this->model = new ArchiveType();
    }

    public function getIndex()
    {
        $this->title = 'Jenis Arsip';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
        * Set form layout
        */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'dwf.archivetype.form_layout';
        $this->form_dialog_size = 'lg';

        /**
        * Set Viewer layout
        */
        $this->viewer_layout = 'dwf.archivetype.view_layout';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $formOptions['groupObjectOptions'] = DwfUtil::toOptions( DwfUtil::getArchGroup(), 'group', '_object');
        $formOptions['subGroupObjectOptions'] = DwfUtil::toOptions( DwfUtil::getArchSubGroup(), 'subGroup', '_object');
        $formOptions['docTypeObjectOptions'] = DwfUtil::toOptions( DwfUtil::getArchDocType(), 'docType', '_object');
        $formOptions['locationObjectOptions'] = DwfUtil::toOptions( DwfUtil::getArchLocation(), 'location', '_object');

        $this->aux_data = $formOptions;

        $this->add_title_fields = '"<h4> Add Archive Type</h4>"';
        $this->view_title_fields = '"Lihat"  + " " + this.callCode';
        $this->update_title_fields = '"Update" +  " " + this.callCode';

        return parent::getIndex();
    }

    public function beforeUpdateForm($population)
    {
        return parent::beforeUpdateForm($population); // TODO: Change the autogenerated stub
    }

    public function beforeUpdate($id, $data)
    {

        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }

    public function beforeSave($data)
    {
        return parent::beforeSave($data); // TODO: Change the autogenerated stub
    }

    public function afterSave($data)
    {
        AuthUtil::registerAclObject($data['menuAuth'], $data['menuTitle'], 'DWF' );
        return parent::afterSave($data); // TODO: Change the autogenerated stub
    }

    public function afterUpdate($id, $data = null)
    {
        AuthUtil::registerAclObject($data['menuAuth'], $data['menuTitle'], 'DWF' );
        return parent::afterUpdate($id, $data); // TODO: Change the autogenerated stub
    }


    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }

    public function postIndex(Request $request)
    {

        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    protected function rowPostProcess($row)
    {

        return parent::rowPostProcess($row);
    }

}
