<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Dwf;

use App\Helpers\App\DwfUtil;
use App\Helpers\App\FileUtil;
use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Dwf\Doc;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Laravel\File;

class DisposalController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

//        $this->res_path = 'views/dwf/repository';
//        $this->yml_file = 'fields';

        $this->res_path = 'models/controllers/dwf';
        $this->yml_file = 'repository_controller';

        $this->entity = 'Document';

        // this must be set to use ACL
        $this->auth_entity = 'dms-repository';

        // set controller path
        $this->controller_base = 'dwf/disposal';

        // set view base to include standard slot
        $this->view_base = 'dwf.disposal';
        $this->model = new Doc();
    }

    public function getIndex()
    {
        $this->title = 'Document Disposal';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);

        $this->template_var = [ 'hasSideNav'=>true ];

        $this->logo = env('APP_LOGO');

        $this->show_title = true;
        $this->viewer_layout = 'dwf.repository.viewlayout';

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'dwf.repository.formlayout';
        $this->form_dialog_size = 'xl';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->can_multi_clone = false;

        $this->print_template = 'document-label';
        $this->print_modal_size = 'lg';

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $formOptions['IOOptions'] = [ ['text'=>'Incoming', 'value'=>'Incoming'], ['text'=>'Outgoing', 'value'=>'Outgoing'] ];
        $formOptions['TipeOptions'] = DwfUtil::toOptions( DwfUtil::getDocType(), 'DocType', 'DocType', false );
        $formOptions['CoyOptions'] = DwfUtil::toOptions( DwfUtil::getCompany(), 'CoyName', 'CoyCode', false );
        $formOptions['RetPerOptions'] = DwfUtil::toOptions( DwfUtil::getYearOptions(), 'Desc', 'DisYr', false );
        $formOptions['DispPerOptions'] = DwfUtil::toOptions( DwfUtil::getYearOptions(), 'Desc', 'DisYr', false );

        $formOptions['TopicObjectOptions'] = DwfUtil::toOptions( DwfUtil::getTopics(), 'Topic', '_object', false );

        $formOptions['selectedSheets'] = 0;
        $formOptions['boxIdInput'] = "``";

        $formOptions['sourceDir'] = "'".env('DEFAULT_SOURCE_DIR')."'";
        $formOptions['scanMode'] = "'copy'";
        $formOptions['scanning'] = "false";

        $formOptions['labelTemplate'] = '`'.file_get_contents( resource_path('views/dwf/repository/labeltemplate.html') ).'`';
        $formOptions['printTemplate'] = '`'.file_get_contents( resource_path('views/dwf/repository/printtemplate.html') ).'`';
        $formOptions['printLabelData'] = "``";

        $this->view_title_fields = '"<h4>View " + this.FCallCode + "</h4>"';
        $this->update_title_fields = '"<h4>Update " + this.FCallCode + "</h4>"';

        $this->aux_data = $formOptions;

        return parent::getIndex();
    }

    public function postIndex(Request $request)
    {
        $this->defOrderField = 'IODate';
        $this->defOrderDir = 'desc';
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {
        $today = date('Y-m-d H:i:s', time());

        return response()->json(
            [
                'IO'=>'Incoming',
                'Status'=>'Active',
                'RetPer'=>2,
                'DispPer'=>5,
                'IODate'=>$today
            ]

        );

    }


    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        $model = $model->orderBy('DispDate', 'asc' )
            ->orderBy('Feature', 'desc' )
            ->orderBy('Topic', 'desc' )
            ->orderBy('Coy', 'desc' );
        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        return parent::beforeSave($data);
    }

    protected function rowPostProcess($row)
    {
        /* modify or add new fields */
        //$row['linkConsult'] = url('clinic/patient/km/'.$row['_id']);
        //$row['linkOp'] = url('clinic/patient/op/'.$row['_id']);

        return parent::rowPostProcess($row);
    }

    public function externalData($data, $request)
    {
        $temp = [];

        for($i = 0; $i < count($data); $i++ ){
            $label = substr($data[$i]['Topic'], 0, 4 );
            $temp[ $label ][] = $data[$i];
        }

        $out = [];
        foreach($temp as $k=>$v){
            $out[] = [
                'label'=>$k,
                'mode'=>'span',
                'children'=>$v
            ];
        }

        return $out;

    }

    public function beforeImportCommit($data)
    {
        $data['IODate'] = ImportUtil::excelDateToNormal($data['IODate']);
        $data['DocDate'] = ImportUtil::excelDateToNormal($data['DocDate']);
        $data['RetDate'] = ImportUtil::excelDateToNormal($data['RetDate']);
        $data['DispDate'] = ImportUtil::excelDateToNormal($data['DispDate']);

        return parent::beforeImportCommit($data); // TODO: Change the autogenerated stub
    }

    public function postDispose(Request $request)
    {
        $sel = $request->input('selected');
        $boxId = $request->input('boxId');

        $ids = [];
        foreach($sel as $s){
            $ids[] = $s['_id'];
        }
        debug($ids);

        $docs = $this->model->whereIn( '_id', $ids )->get();

        debug($docs->toArray());

        foreach ($docs as $doc){
            $doc->Location = $boxId;
            $doc->BoxId = $boxId;
            $doc->Status = 'Disposed';
            $doc->save();
        }

        return response()->json(['result'=>'OK', 'message'=>count($docs).' document(s) dispatched.' ]);

    }


}
