<?php

namespace App\Http\Middleware;

use App\Helpers\AuthUtil;
use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class CheckRole extends Middleware
{

    public function handle($request, Closure $next, ...$guards)
    {
        $user = $request->user()->toArray();
        $redir = AuthUtil::getRoleRedirect($user['roleId']);
        debug($user['roleId']);
        debug($redir);
        debug($guards);

        return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub
    }


}
