<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Dwf\Admin;

use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Dwf\CallCode;
use App\Models\Dwf\Doc;
use App\Models\Dwf\DocClass;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class DocClassController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

//        $this->res_path = 'views/dwf/admin/docclass';
//        $this->yml_file = 'fields';

        $this->res_path = 'models/controllers/dwf/admin';
        $this->yml_file = 'docclass_controller';

        $this->entity = 'Document Class';

        $this->auth_entity = 'dms-repository';
        // set controller path
        $this->controller_base = 'dwf/admin/docclass';

        $this->defOrderField = 'classCode';
        $this->defOrderDir = 'asc';
        // set view base to include standard slot
        $this->view_base = 'dwf.admin.docclass';
        $this->model = new DocClass();
    }

    public function getIndex()
    {
        $this->title = 'Kode Klasifikasi';

        $cname = substr(strrchr(get_class($this), '\\'), 1);

        $this->controller_name = str_replace('Controller', '', $cname);

        $this->template_var = [ 'hasSideNav'=>true ];

        $this->logo = env('APP_LOGO');

        $this->show_title = true;

        $this->viewer_layout = 'dwf.admin.docclass.formlayout';

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'dwf.admin.docclass.formlayout';
        $this->form_dialog_size = 'md';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->can_multi_clone = false;
        $this->can_clone = false;

        $this->print_template = 'document-label';
        $this->print_modal_size = 'lg';

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $this->aux_data = $formOptions;

        return parent::getIndex();
    }

    public function postIndex(Request $request)
    {
//        $this->defOrderField = 'IODate';
//        $this->defOrderDir = 'desc';
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {
        $this->def_param['Status'] = 'Active';
        return parent::getParam(); // TODO: Change the autogenerated stub
    }

    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        return parent::beforeSave($data);
    }

    protected function rowPostProcess($row)
    {
        /* modify or add new fields */
        //$row['linkConsult'] = url('clinic/patient/km/'.$row['_id']);
        //$row['linkOp'] = url('clinic/patient/op/'.$row['_id']);

        return parent::rowPostProcess($row);
    }

    public function beforeImportCommit($data)
    {

        return parent::beforeImportCommit($data); // TODO: Change the autogenerated stub
    }


}
