<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Ecf;

use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Helpers\Injector;
use App\Models\Ecf\SalesOrder;
// use App\Models\Inventory\InventoryItem;
use App\Http\Controllers\Core\AdminController;
use App\Models\Ecf\Invoice;
use App\Models\Reference\Product;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class InvoiceController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/ecf';

        $this->yml_file = 'invoice_controller';

        $this->entity = 'Invoice';

        $this->auth_entity = 'ecf-transaction-invoice';

        $this->controller_base = 'ecf/invoice';

        $this->view_base = 'ecf.invoice';

        $this->model = new Invoice();
        $this->model1 = new SalesOrder();
        // $this->model2 = new InventoryItem();
        $this->model3 = new Product();
    }

    public function getIndex()
    {
        $this->title = 'Invoice';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
        * Set form layout
        */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'ecf.invoice.form_layout';
        $this->form_dialog_size = 'lg';

        /**
        * Set Viewer layout
        */
        $this->viewer_layout = 'ecf.invoice.view_layout';
        $this->viewer_dialog_size = 'lg';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->add_as_page = false;
        $this->edit_as_page = false;
        $this->with_advanced_search = false;
        $this->add_filler = true;

        return parent::getIndex();
    }

    public function setupInjector($uiOptions, $data = null)
    {
        return parent::setupInjector($uiOptions, $data); // TODO: Change the autogenerated stub
    }

    public function setupFormOptions($formOptions, $data = null)
    {
        $formOptions['statusOptions'] = [
            ['text' => 'OPEN', 'value' => 'OPEN'],
            ['text' => 'PAID', 'value' => 'PAID'],
            ['text' => 'REJECTED', 'value' => 'REJECTED'],

        ];
        return parent::setupFormOptions($formOptions, $data); // TODO: Change the autogenerated stub
    }

    public function getAdd(Request $request, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        $this->title = __('Add').' '.$this->entity;

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'ecf.invoice.form_layout';

        $this->runAcl();
        $this->runUrlSet('add');
        $this->runPageViewSet('add');

        $uiOptions = [];

        $uiOptions = $this->setupInjector($uiOptions);

        $formOptions = Util::loadResYaml($this->yml_file, $this->res_path)->toFormOption();

        $formOptions = $this->setupFormOptions($formOptions);

        $this->aux_data = array_merge( $uiOptions ,$formOptions);

        $this->page_redirect_after_save = true;

        return parent::getAdd($request, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function getEdit(Request $request, $id, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        $item = $this->model->find($id);

        $this->item_id = $item->_id;

        $this->title = __('Edit').' '.$item->_id;

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'ecf.invoice.form_layout';

        $this->runAcl();
        $this->runUrlSet('edit');
        $this->runPageViewSet('edit');

        $uiOptions = [];

        $uiOptions = $this->setupInjector($uiOptions);

        $formOptions = Util::loadResYaml($this->yml_file, $this->res_path)->toFormOption();

        $formOptions = $this->setupFormOptions($formOptions);

        $this->aux_data = array_merge( $uiOptions ,$formOptions);

        $this->page_redirect_after_save = true;

        return parent::getEdit($request, $id, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function getView(Request $request, $id, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        return parent::getView($request, $id, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function postClone(Request $request)
    {
        $this->revision_key = 'requestNo';
        return parent::postClone($request);
    }

    public function postIndex(Request $request)
    {
//        $this->defOrderField = 'Item';
//        $this->defOrderDir = 'asc';
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        return parent::beforeSave($data);
    }

    public function beforeUpdateForm($population)
    {
        return parent::beforeUpdateForm($population); // TODO: Change the autogenerated stub
    }

    public function beforeUpdate($id, $data)
    {
        $cartSession = $data["cartSession"];
        if($data["status"] == "PAID"){
            $this->model1->where("cartSession","=", $cartSession)
            ->update(
                ["status" => "PAID"]
            );

            $inventory= $this->model2::where('cartSession', $cartSession)->get();

            foreach($inventory as $items){
                $productCode = $items->productCode;
                $this->model2->where("productCode","=", $productCode)
                ->update(
                    [
                        "status" => "CONFIRMED",
                        "lastStock" => $items->stock
                    ]
                );
                $product = $this->model3::where("productCode","=", $productCode)->first();

                $this->model3->where("productCode","=", $productCode)
                ->update(
                    [
                        "status" => "CONFIRMED",
                        "lastStock" => $product->stock
                    ]
                );
            }
        }elseif($data["status"] == "REJECTED"){
            $this->model1->where("cartSession","=", $cartSession)
            ->update(
                ["status" => "REJECTED"]
            );

            $inventory= $this->model2::where('cartSession', $cartSession)->get();

            foreach($inventory as $items){
                $productCode = $items->productCode;
                $product = $this->model3::where("productCode","=", $productCode)->first();

                $last_stock = $product->lastStock;

                $this->model2->where("productCode","=", $productCode)
                ->update(
                    [
                        "status" => "CONFIRMED",
                        "stock" => $items->lastStock
                    ]
                );


                $this->model3->where("productCode","=", $productCode)
                ->update(
                    [
                        "status" => "CONFIRMED",
                        "stock" => $last_stock
                    ]
                );
            }

        }
        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }

    protected function rowPostProcess($row)
    {

        return parent::rowPostProcess($row);
    }

}
