<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Ecf;

use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Helpers\Injector;
use App\Http\Controllers\Core\AdminController;
use App\Models\Ecf\Product;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/ecf';

        $this->yml_file = 'product_controller';

        $this->entity = 'Product';

        $this->auth_entity = 'ecf-product';

        $this->controller_base = 'ecf/product';

        $this->view_base = 'ecf.product';

        $this->title_fields = 'productName';

        $this->model = new Product();
    }

    public function getIndex()
    {
        $this->title = 'Product';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
        * Set form layout
        */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'ecf.product.form_layout';
        $this->form_dialog_size = 'md';

        /**
        * Set Viewer layout
        */
        $this->viewer_layout = 'ecf.product.view_layout';
        $this->viewer_dialog_size = 'md';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->with_advanced_search = true;

        $this->extra_query = [
            'companyId'=>'',
            'companyName'=>'',
            'productName'=>'',
            'typeproduct'=>'',
            'description'=>'',
            'price'=>''
        ];

        $this->add_as_page = false;
        $this->edit_as_page = false;

        $this->add_filler = true;

        return parent::getIndex();
    }

    public function setupInjector($uiOptions, $data = null)
    {
        return parent::setupInjector($uiOptions, $data); // TODO: Change the autogenerated stub
    }

    public function setupFormOptions($formOptions, $data = null)
    {
        $formOptions['typeproductOptions'] = [ 
            [ 'text'=> "Barang", 'value'=> "Barang" ], 
            [ 'text'=> "Bahan Baku", 'value'=> "Bahan Baku" ], 
            [ 'text'=> "Kebutuhan Sehari-hari", 'value'=> "Kebutuhan Sehari-hari" ], 
            [ 'text'=> "Jasa", 'value'=> "Jasa" ], 
            [ 'text'=> "Modal", 'value'=> "Modal" ] 
        ];

        return parent::setupFormOptions($formOptions, $data); // TODO: Change the autogenerated stub
    }

    public function getAdd(Request $request, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        $this->title = __('Add').' '.$this->entity;

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'ecf.product.form_layout';

        $this->runAcl();
        $this->runUrlSet('add');
        $this->runPageViewSet('add');

        $uiOptions = [];

        $uiOptions = $this->setupInjector($uiOptions);

        $formOptions = Util::loadResYaml($this->yml_file, $this->res_path)->toFormOption();

        $formOptions = $this->setupFormOptions($formOptions);

        $this->aux_data = array_merge( $uiOptions ,$formOptions);

        $this->page_redirect_after_save = true;

        return parent::getAdd($request, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function getEdit(Request $request, $id, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        $item = $this->model->find($id);

        $this->item_id = $item->_id;

        $this->title = __('Edit').' '.$item->_id;

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'ecf.product.form_layout';

        $this->runAcl();
        $this->runUrlSet('edit');
        $this->runPageViewSet('edit');

        $uiOptions = [];

        $uiOptions = $this->setupInjector($uiOptions);

        $formOptions = Util::loadResYaml($this->yml_file, $this->res_path)->toFormOption();

        $formOptions = $this->setupFormOptions($formOptions);

        $this->aux_data = array_merge( $uiOptions ,$formOptions);

        $this->page_redirect_after_save = true;

        return parent::getEdit($request, $id, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function getView(Request $request, $id, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        return parent::getView($request, $id, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function postClone(Request $request)
    {
        $this->revision_key = 'requestNo';
        return parent::postClone($request);
    }

    public function postIndex(Request $request)
    {
//        $this->defOrderField = 'Item';
//        $this->defOrderDir = 'asc';
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function additionalQuery($model, Request $request)
    {
        $adv = $request->get('advancedSearch') ?? false;
        $ext = $request->get('extraData') ?? false;
        if( $adv && $ext &&  (isset($adv['enable']) && $adv['enable']) && $adv['isOpen']){

            if( isset($ext['productName']) && $ext['productName'] != '' ){
                $productName = explode(',', $ext['productName'] );

                $model = $model->where(function($q) use ( $productName) {
                    for($i = 0; $i < count($productName); $i++){
                        if($i == 0){
                            $q = $q->where('productName','like','%'.$productName[$i].'%');
                        }else{
                            $q = $q->orWhere('productName','like','%'.$productName[$i].'%');
                        }
                    }
                });
            }

            if( isset($ext['typeproduct']) && $ext['typeproduct'] != '' ){
                $typeproduct = explode(',', $ext['typeproduct'] );

                $model = $model->where(function($q) use ( $typeproduct) {
                    for($i = 0; $i < count($typeproduct); $i++){
                        if($i == 0){
                            $q = $q->where('typeproduct','like','%'.$typeproduct[$i].'%');
                        }else{
                            $q = $q->orWhere('typeproduct','like','%'.$typeproduct[$i].'%');
                        }
                    }
                });
            }

            if( isset($ext['companyId']) && $ext['companyId'] != '' ){
                $companyId = explode(',', $ext['companyId'] );

                $model = $model->where(function($q) use ( $companyId) {
                    for($i = 0; $i < count($companyId); $i++){
                        if($i == 0){
                            $q = $q->where('companyId','like','%'.$companyId[$i].'%');
                        }else{
                            $q = $q->orWhere('companyId','like','%'.$companyId[$i].'%');
                        }
                    }
                });
            }



        }

        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        return parent::beforeSave($data);
    }

    public function beforeUpdateForm($population)
    {
        return parent::beforeUpdateForm($population); // TODO: Change the autogenerated stub
    }

    public function beforeUpdate($id, $data)
    {

        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }

    protected function rowPostProcess($row)
    {

        return parent::rowPostProcess($row);
    }

}
