<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Sfm\Store;

use App\Helpers\App\SfmUtil;
use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\RefUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Http\Controllers\Core\PublicController;
use App\Models\Core\Mongo\User;
use App\Models\Reference\Product;
use App\Models\Ecf\Campaign;
use Illuminate\Http\Request;
use App\Helpers\NumberUtil;
use Illuminate\Support\Facades\Storage;

class ProductCatalogController extends PublicController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/sfm/product';

        $this->yml_file = 'catalog_controller';

        $this->entity = 'Product';

        $this->auth_entity = 'sfm-product-catalog';

        $this->controller_base = 'catalog';

        $this->view_base = 'sfm.product.catalog';

        $this->model = new Product();
        // $this->model = new Campaign();
    }

    public function getIndex()
    {
        $this->title = __('Katalog Bisnis TEST');

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
        * Set form layout
        */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'sfm.product.catalog.form_layout';
        $this->form_dialog_size = 'xl';

        // /**
        // * Set Viewer layout
        // */

        $this->viewer_layout = 'sfm.product.catalog.view_layout';
        $this->viewer_dialog_size = 'xl';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->add_as_page = false;
        $this->edit_as_page = false;
        $this->with_advanced_search = false;
        $this->can_update = true;
        $this->can_view = true;

        $this->update_title_fields = '"<h4>'.__('Edit')." ".'" + this.productName + "</h4>"';
        $this->view_title_fields = '"<h4>'.__('View')." ".'" + this.productName + "</h4>"';

        $this->page_refresh_button = true;

        $this->table_component = 'grid-view';

        $this->grid_item_view = 'sfm.product.catalog.product_item';

        $this->grid_card_layout = 'card-columns';

        //$this->grid_card_class = 'w-25';
        $this->bootstrap_version = 5;

        $this->layout = 'layouts.dojek1_page';

        return parent::getIndex();
    }

    public function getList(Request $request, $keyword0, $keyword1 = null, $keyword2 = null)
    {

        $this->title = __('Product Catalog');

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
         * Set form layout
         */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'sfm.product.catalog.form_layout';
        $this->form_dialog_size = 'xl';

        /**
         * Set Viewer layout
         */
        $this->viewer_layout = 'sfm.product.catalog.view_layout';
        $this->viewer_dialog_size = 'xl';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->add_as_page = false;
        $this->edit_as_page = false;
        $this->with_advanced_search = false;
        $this->update_title_fields = '"<h4>'.__('Edit')." ".'" + this.productName + "</h4>"';
        $this->view_title_fields = '"<h4>'.__('View')." ".'" + this.productName + "</h4>"';

        $this->page_refresh_button = true;

        $this->table_component = 'grid-view';

        $this->grid_item_view = 'sfm.product.catalog.product_item';

        $this->grid_card_layout = 'card-columns';

        //$this->grid_card_class = 'w-25';
        $this->bootstrap_version = 5;

        return parent::getList($request, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function setupInjector($uiOptions, $data = null)
    {
        return parent::setupInjector($uiOptions, $data); // TODO: Change the autogenerated stub
    }

    public function setupFormOptions($formOptions, $data = null)
    {
        $formOptions['unitOptions'] = SfmUtil::toOptions(SfmUtil::getUnits(),'uom','uom', true);
        $formOptions['categoryOptions'] = SfmUtil::toOptions(SfmUtil::getCategories(),['category'],'categoryCode', true);
        $formOptions['currencyOptions'] = RefUtil::toOptions(RefUtil::getCurrency(), 'name','name', true);

        $formOptions['cartObject'] = "{}";
        $formOptions['cartSubTotal'] = 0;
        $formOptions['cartQty'] = 1;
        $formOptions['cartPrice'] = 0;
        $formOptions['cartNote'] = "''";



        return parent::setupFormOptions($formOptions, $data); // TODO: Change the autogenerated stub
    }

    public function getAdd(Request $request, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        $this->title = __('Add').' '.$this->entity;

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'sfm.product.catalog.form_layout';

        $this->runAcl();
        $this->runUrlSet('add');
        $this->runPageViewSet('add');

        $uiOptions = [];

        $uiOptions = $this->setupInjector($uiOptions);

        $formOptions = Util::loadResYaml($this->yml_file, $this->res_path)->toFormOption();

        $formOptions = $this->setupFormOptions($formOptions);

        $this->aux_data = array_merge( $uiOptions ,$formOptions);

        $this->page_redirect_after_save = true;

        return parent::getAdd($request, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function getEdit(Request $request, $id, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        $item = $this->model->find($id);

        $this->item_id = $item->_id;

        $this->title = __('Edit').' '.$item->productName;

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'sfm.product.catalog.form_layout';

        $this->runAcl();
        $this->runUrlSet('edit');
        $this->runPageViewSet('edit');

        $this->page_redirect_after_save = true;

        return parent::getEdit($request, $id, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function getView(Request $request, $id, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        $item = $this->model->find($id);

        $this->item_id = $id;

        $this->title = ' ';

        $this->show_title = false;

        /* Use custom form layout */
        $this->viewer_view = 'form.viewhtml'; // use plain html
        $this->viewer_layout = 'sfm.product.catalog.view_layout';

        $this->runAcl();
        $this->runUrlSet('edit');
        $this->runPageViewSet('page');

        $this->viewer_can_print = false;

        $this->page_redirect_after_save = true;


        return parent::getView($request, $id, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }


    public function postClone(Request $request)
    {
        $this->revision_key = 'requestNo';
        return parent::postClone($request);
    }

    public function postIndex(Request $request)
    {

        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    // public function additionalQuery($model, Request $request)
    // {
    //     $model['rate'] = NumberUtil::decimal($model['rate']);
    //     return parent::additionalQuery($model, $request); // TODO: Change the autogenerated stub
    // }
    public function additionalQuery($model, Request $request)
    {
        // $input = $request->all();
        // print_r($input);
        // $keyword = "nusantara";
        // $keyword = $request->keyword;
        // $request->get('keyword');
        // $keyword = $input->keyword;
        // print_r("test");
        // print_r($request);
        // $request->get("keyword");
        // $keyword = Input::get('keyword');
        $keyword = $request->input('keyword');

        if(isset($keyword)){
            // $keyword = "teh";
            $model = $model->where('productName','LIKE','%'.strtoupper($keyword).'%' )
//            ->groupBy('productName')
            ->orderBy('orderTimestamp', 'desc');
                // $model['rate'] = NumberUtil::decimal($model['rate']);
            return $model;
        }else{
            // $keyword = "nusantara";
            $model = $model->where('productName','LIKE','%'.strtoupper($keyword).'%' )
//            ->groupBy('productName')
            ->orderBy('orderTimestamp', 'desc');
                // $model['rate'] = NumberUtil::decimal($model['rate']);
            return $model;
            // $model['rate'] = NumberUtil::decimal($model['rate']);
            // return parent::additionalQuery($model, $request); // TODO: Change the autogenerated stub
        }
    }
    public function beforeUpdateForm($population)
    {
        return parent::beforeUpdateForm($population); // TODO: Change the autogenerated stub
    }

    public function beforeUpdate($id, $data)
    {

        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }

    public function beforeSave($data)
    {

        return parent::beforeSave($data); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }

    protected function rowPostProcess($row)
    {

        return parent::rowPostProcess($row);
    }

}
