<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Dcs\Scoring;

use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Core\Mongo\User;
use App\Models\Dcs\Scoring\PointValue;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PointController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/dcs/scoring';

        $this->yml_file = 'point_controller';

        $this->entity = 'Point';

        $this->auth_entity = 'scoring-point';

        $this->controller_base = 'dcs/scoring/point';

        $this->view_base = 'dcs.scoring.point';

        $this->model = new PointValue();
    }

    public function getIndex()
    {
        $this->title = 'Scoring Point Value';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
        * Set form layout
        */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'dcs.scoring.point.form_layout';
        $this->form_dialog_size = 'lg';

        /**
        * Set Viewer layout
        */
        $this->viewer_layout = 'dcs.scoring.point.view_layout';
        $this->viewer_dialog_size = 'lg';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->can_multi_clone = false;
        $this->can_multi_delete = false;
        $this->can_clone = false;
        $this->can_delete = false;
        $this->can_upload = false;
        $this->can_print = false;

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $formOptions['methodOptions'] = [[ 'value'=> 'ADL', 'text'=> 'ADL' ],[ 'value'=> 'IADL', 'text'=> 'IADL'], [ 'value'=> 'GDS', 'text'=> 'GDS' ],[ 'value'=> 'Demensia', 'text'=> 'Demensia'],[ 'value'=> 'Disabilitas', 'text'=> 'Disabilitas'], [ 'value'=> 'CFS', 'text'=> 'CFS']];

        $this->aux_data = $formOptions;

        $this->add_title_fields = '"<h4> Add Scoring Category</h4>"';
        $this->view_title_fields = '"Lihat"  + " " + this.category';
        $this->update_title_fields = '"Update" +  " " + this.category';

        return parent::getIndex();
    }

    public function additionalQuery($model, Request $request)
    {
        $model = $model->orderBy('method', 'ASC')->orderBy('score1', 'ASC');

        return parent::additionalQuery($model, $request); // TODO: Change the autogenerated stub
    }

    public function beforeUpdateForm($population)
    {
        return parent::beforeUpdateForm($population); // TODO: Change the autogenerated stub
    }

    public function beforeUpdate($id, $data)
    {

        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }

    public function beforeSave($data)
    {

        return parent::beforeSave($data); // TODO: Change the autogenerated stub
    }


    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }

    public function postIndex(Request $request)
    {

        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    protected function rowPostProcess($row)
    {

        return parent::rowPostProcess($row);
    }

}
