table:
    -
        label: Action
        name: _id
        show: true
        search: false
        sort: false
        datatype: text
        uniqueId: true
        row_text_alignment: text-left
        column_classes: col_action
        thClass: 'text-center text-50'
    -
        label: Picture
        name: picture
        show: true
        search: false
        sort: false
        datatype: imagearray
        column_classes: text-center text-75
    -
        label: SKU
        name: productCode
        show: true
        search: true
        sort: false
        datatype: text
        column_classes: text-center text-150
    -
        label: Product Name
        name: productName
        show: true
        search: true
        sort: false
        datatype: text
        column_classes: text-center text-200
    # -
    #     label: Category
    #     name: category
    #     show: true
    #     search: false
    #     sort: false
    #     datatype: text
    #     column_classes: text-center text-150
    # -
    #     label: Currency
    #     name: currency
    #     show: true
    #     search: false
    #     sort: false
    #     datatype: text
    #     column_classes: text-center text-50

    -
    #     label: Products
    #     name: products
    #     show: true
    #     search: true
    #     sort: false
    #     filter: false
    #     datatype: tagsinput
    #     row_text_alignment: text-center
    #     column_classes: 'text-center text-70'
    #     thClass: ''
    # -
        label: Price
        name: price
        show: true
        search: false
        sort: false
        datatype: text
        column_classes: text-right text-100
    # -
    #     label: Unit
    #     name: unit
    #     show: true
    #     search: false
    #     sort: false
    #     datatype: text
    #     column_classes: text-center text-75
    -
        label: Rating
        name: rate
        show: true
        search: false
        sort: false
        datatype: text
        column_classes: text-center text-50
    -
        label: Stock
        name: stock
        show: true
        search: false
        sort: false
        datatype: text
        column_classes: text-center text-50
    -
        label: Level
        name: level
        show: true
        search: false
        sort: false
        datatype: text
        column_classes: text-center text-50
    -
        label: Weight
        name: weight
        show: true
        search: false
        sort: false
        datatype: text
        column_classes: text-center text-50
    # -
    #     label: Unit
    #     name: unit
    #     show: true
    #     search: false
    #     sort: false
    #     datatype: text
    #     column_classes: text-center text-75
    -
        label: Description
        name: description
        show: true
        search: false
        sort: false
        datatype: text
    -
        label: Specifications
        name: specifications
        show: false
        search: false
        sort: false
        datatype: text
form:
    -
        label: ''
        name: _id
        create: false
        edit: false
        type: text
        model: _id
        default: ''
        validator: required
        param: {}
        attr: {}
    -
        label: Vendor
        name: vendorCode
        create: true
        edit: true
        type: simpleselect
        model: vendorCode
        default: ''
        validator: required
        param: {}
        attr: {}
    -
        label: SKU
        name: productCode
        create: true
        edit: true
        type: text
        model: productCode
        default: ''
        validator: required
        param: {}
        attr: {}
    -
        label: Product Name
        name: productName
        create: true
        edit: true
        type: text
        model: productName
        default: ''
        validator: required
        param: {}
        attr: {}
    -
        label: Category
        name: category
        create: true
        edit: true
        type: simpleselect
        model: category
        default: ''
        validator: required
        param: {}
        attr: {}
    -
        label: Price
        name: price
        create: true
        edit: true
        type: currency
        model: price
        default: '0'
        validator: required
        prepend: select
        currency: currency
        select_model: currency
        select_class: text-75
        param: {}
        attr: {}
    -
        label: Picture
        name: picture
        create: true
        edit: true
        type: attachmentupload
        model: picture
        default: ''
        show_list: true
        param:
            url: "api/v1/core/upload"
            paramName: "file"
        attr: { class: "form-data", buttonlabel: "Upload Picture" }
    -
        label: Unit Count
        name: unitCount
        create: true
        edit: true
        type: number
        model: unitCount
        default: ''
        validator: required
        param: {}
        attr: {}
    -
        label: Rating
        name: rate
        create: true
        edit: true
        type: number
        model: rate
        default: ''
        validator:
        param: {}
        attr: {}
    -
        label: Level
        name: level
        create: true
        edit: true
        type: text
        model: level
        default: ''
        validator:
        param: {}
        attr: {}
    -
        label: Stock
        name: stock
        create: true
        edit: true
        type: number
        model: stock
        default: '0'
        validator:
        param: {}
        attr: {}
    -
        label: 'Weight'
        name: weight
        create: true
        edit: true
        type: number
        model: weight
        default: ''
        validator:
        param: {}
        attr: {}
    -
        label: 'Tag '
        name: products
        create: true
        edit: true
        type: tagsinput
        model: products
        default: ''
        validator: ''
        ordered: false
        show_table_header: true
        modal_size: md
        placeholder: 'Products'
        param:
            url: api/v1/core/auto/tag
        attr: {}
    -
        label: Unit
        name: unit
        create: true
        edit: true
        type: simpleselect
        model: unit
        default: ''
        validator: required
        param: {}
        attr: {}
    -
        label: Description
        name: description
        create: true
        edit: true
        type: markdown
        model: description
        default: ''
        validator: required
        param: {}
        attr: {}
vue:
    -
        model: _id
        visible: false
        type: string
        default: ''
        search: true
        im: false
        ex: false
    -
        model: vendorCode
        visible: true
        type: string
        default: ''
        search: true
        im: true
        ex: true
    -
        model: productCode
        visible: true
        type: string
        default: ''
        search: true
        im: true
        ex: true
    -
        model: productName
        visible: true
        type: string
        default: ''
        search: true
        im: true
        ex: true
    -
        model: category
        visible: true
        type: array
        default: []
        search: true
        im: true
        ex: true
    -
        model: currency
        visible: true
        type: string
        default: 'IDR'
        search: true
        im: true
        ex: true
    -
        model: price
        visible: true
        type: string
        default: ''
        search: true
        im: true
        ex: true
    -
        model: picture
        visible: true
        type: array
        default: []
        search: true
        im: true
        ex: true
    -
        model: pictureObjects
        visible: true
        type: array
        default: []
        search: true
        im: true
        ex: true
    -
        model: unit
        visible: true
        type: string
        default: ''
        search: true
        im: true
        ex: true
    -
        model: unitCount
        visible: true
        type: double
        default: 1
        search: true
        im: true
        ex: true
    -
        model: level
        visible: true
        type: string
        default: 'TOPANG'
        search: true
        im: true
        ex: true
    -
        model: rate
        visible: true
        type: number
        step: 0.5
        default: 1
        search: true
        im: true
        ex: true
    -
        model: stock
        visible: true
        type: double
        default: 0
        search: true
        im: true
        ex: true
    -
        model: stock
        visible: true
        type: double
        default: 0
        search: true
        im: true
        ex: true
    -
        model: products
        visible: true
        type: string
        default: ''
    -
        model: weight
        visible: true
        type: string
        default: ''
    -
        model: description
        visible: true
        type: string
        default: ''
        search: true
        im: true
        ex: true
    -
        model: specifications
        visible: true
        type: array
        default: []
        search: true
        im: true
        ex: true
view:
    -
        label: ''
        name: _id
        visible: false
        type: text
        model: _id
    -
        label: Vendor Code
        name: vendorCode
        visible: true
        type: text
        model: code
    -
        label: SKU
        name: productCode
        visible: true
        type: text
        model: productCode
    -
        label: Product Name
        name: productName
        visible: true
        type: text
        model: productName
    -
        label: Category
        name: category
        visible: false
        type: text
        model: category
    -
        label: Currency
        name: currency
        visible: true
        type: text
        model: currency
    -
        label: Price
        name: price
        visible: true
        type: text
        model: price
    -
        label: Unit
        name: unit
        visible: false
        type: text
        model: unit
    -
        label: Level
        name: level
        visible: false
        type: text
        model: level
    -
        label: Rating
        name: rate
        visible: false
        type: number
        model: rate
    -
        label: Stock
        name: stock
        visible: false
        type: text
        model: stock
    -
        label: Weight
        name: weight
        visible: false
        type: text
        model: weight
    -
        label: ' '
        name: products
        model: products
        visible: true
        type: tagsinput
        default: ''
    -
        label: Unit Count
        name: unitCount
        visible: false
        type: text
        model: unitCount
    -
        label: Picture
        name: picture
        visible: true
        type: squaresingleimage
        model: picture
    -
        label: Description
        name: description
        visible: true
        type: text
        model: description
    -
        label: Specifications
        name: specifications
        visible: true
        type: arrayview
        model: specifications
