<?php

namespace App\Http\Controllers\Api\Sfm\Store;

use App\Http\Controllers\Api\Core\ApiAdminController;
use App\Models\Sfm\Store\ShoppingCartAttribute;

class ShoppingCartAttributeController extends ApiAdminController
{

    public function __construct()
    {
        $this->controller_name = strtolower( str_replace('Controller', '', get_class()) );
        $this->model = new ShoppingCartAttribute();

        $this->res_path = 'models/sfm/store'; // under resources ,ie: resources/models
        $this->yml_file = 'shoppingcartcontroller'; // name of yml ,ie: member.yml
        $this->entity = 'shoppingcartattribute';

    }

    public function beforeOutput($data)
    {
        //$data['addOut'] = "ADD BEFORE OUTPUT";
        return parent::beforeOutput($data); // TODO: Change the autogenerated stub
    }


    public function beforeSave($data)
    {
        //$data['beforeSave'] = 'BEFORE';
        return parent::beforeSave($data); // TODO: Change the autogenerated stub
    }

    public function afterSave($data)
    {
        //$data['afterSave'] = 'AFTER';
        return parent::afterSave($data); // TODO: Change the autogenerated stub
    }


}
