<div>

{!! $profileExtId ?? '' !!}
{!! $ownerProfileName ?? '' !!}
{!! $ownerProfileEmail ?? '' !!}
{!! $ownerProfilePlaceOfBirth ?? '' !!}
{!! $ownerProfileDateOfBirth ?? '' !!}
{!! $ownerProfileMobile ?? '' !!}
{!! $ownerProfileGender ?? '' !!}
{!! $ownerProfileNik ?? '' !!}
{!! $ownerProfileAddress ?? '' !!}
{!! $ownerProfileProvince ?? '' !!}
{!! $ownerProfileCity ?? '' !!}
{!! $ownerProfileZip ?? '' !!}
{!! $ownerProfilePhoto ?? '' !!}
{!! $ownerProfileIdPhoto ?? '' !!}
{!! $ownerProfileIdType ?? '' !!}
{!! $ownerProfilePhone ?? '' !!}
{!! $ownerProfileKelurahan ?? '' !!}
{!! $penyeliaExtId ?? '' !!}
{!! $penyeliaName ?? '' !!}
{!! $penyeliaEmail ?? '' !!}
{!! $penyeliaPlaceOfBirth ?? '' !!}
{!! $penyeliaDateOfBirth ?? '' !!}
{!! $penyeliaMobile ?? '' !!}
{!! $penyeliaGender ?? '' !!}
{!! $penyeliaNik ?? '' !!}
{!! $penyeliaAddress ?? '' !!}
{!! $penyeliaProvince ?? '' !!}
{!! $penyeliaCity ?? '' !!}
{!! $penyeliaZip ?? '' !!}
{!! $penyeliaPhoto ?? '' !!}
{!! $penyeliaIdPhoto ?? '' !!}
{!! $penyeliaIdType ?? '' !!}
{!! $penyeliaPhone ?? '' !!}
{!! $penyeliaKelurahan ?? '' !!}
{!! $bizFactories ?? '' !!}
{!! $bizOutlets ?? '' !!}
</div>