<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Fms;

use App\Helpers\App\FmsUtil;
use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Fms\MedAdministeredDrug;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class MedAdministeredDrugController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/fms';

        $this->yml_file = 'medadministereddrug_controller';

        $this->entity = 'Med Administered Drug';

        $this->auth_entity = 'fms-med-administered-drug';

        $this->controller_base = 'fms/med-administered-drug';

        $this->view_base = 'fms.medadministereddrug';

        $this->model = new MedAdministeredDrug();
    }

    public function getIndex()
    {
        $this->title = 'Med Administered Drug';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
        * Set form layout
        */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'fms.medadministereddrug.form_layout';
        $this->form_dialog_size = 'lg';

        /**
        * Set Viewer layout
        */
        $this->viewer_layout = 'fms.medadministereddrug.view_layout';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();


        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();
        $formOptions['farmIdOptions'] = FmsUtil::toOptions( FmsUtil::getFarms( Auth::user()->_id ), 'farmName', '_id', true ) ;
        $formOptions['farmObjectOptions'] = FmsUtil::toOptions( FmsUtil::getFarms( Auth::user()->_id ), 'farmName', '_object', true ) ;

        $this->aux_data = $formOptions;
        $this->print_template = 'data-card';
        $this->add_title_fields = '"<h4> Add Med Administered Drug</h4>"';
        $this->view_title_fields = '"Lihat"  + " " + this.namaLansia';
        $this->update_title_fields = '"Update" +  " " + this.namaLansia';

        return parent::getIndex();
    }

    public function beforeUpdateForm($population)
    {
        return parent::beforeUpdateForm($population); // TODO: Change the autogenerated stub
    }

    public function beforeUpdate($id, $data)
    {

        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }

    public function beforeSave($data)
    {

        return parent::beforeSave($data); // TODO: Change the autogenerated stub
    }


    public function getParam()
    {

        $this->def_param['farmId'] = Auth::user()->bizUnitId ?? '';
        $this->def_param['officerId'] = Auth::user()->_id;
        $this->def_param['officerName'] = Auth::user()->name;
        return parent::getParam(); // TODO: Change the autogenerated stub
    }

    public function postIndex(Request $request)
    {

        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    protected function rowPostProcess($row)
    {

        return parent::rowPostProcess($row);
    }

}
