<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Fms;

use App\Helpers\App\FmsUtil;
use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Fms\Farm;
use App\Models\Fms\Reproduction;
use App\Models\Core\Mongo\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ReproductionController extends AdminController

{
    var $farms = [];

    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/fms';

        $this->yml_file = 'reproduction_controller';

        $this->entity = 'Reproduction';

        $this->auth_entity = 'fms-reproduction';

        $this->controller_base = 'fms/reproduction';

        $this->view_base = 'fms.reproduction';

        $this->model = new Reproduction();
    }

    public function getIndex()
    {
        $this->title = 'Reproduction';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
        * Set form layout
        */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'fms.reproduction.form_layout';
        $this->form_dialog_size = 'md';

        /**
        * Set Viewer layout
        */
        $this->viewer_layout = 'fms.reproduction.view_layout';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->print_template = 'data-card';
        $this->title_fields = 'farmNo';
        $this->pdf_title_fields = 'farmNo';

        return parent::getIndex();
    }

    public function setupFormOptions($formOptions, $data = null)
    {
        $masterId = Auth::user()->masterId ?? '';

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();
        $formOptions['farmIdOptions'] = FmsUtil::toOptions( FmsUtil::getFarms( Auth::user()->_id ), 'farmName', '_id', true ) ;
        $formOptions['farmObjectOptions'] = FmsUtil::toOptions( FmsUtil::getFarms( $masterId ), 'farmName', '_object', false ) ;
        $formOptions['bornDiffOptions'] = [ [ 'text'=> "Normal", 'value'=> "Normal" ], [ 'text'=> "Ditarik", 'value'=> "Ditarik" ], [ 'text'=> "Distokia", 'value'=> "Distokia" ], [ 'text'=> "Caesar", 'value'=> "Caesar" ] ];
        $formOptions['calfDiffOptions'] = [ [ 'text'=> "Normal", 'value'=> "Normal" ], [ 'text'=> "Ditarik", 'value'=> "Ditarik" ], [ 'text'=> "Distokia", 'value'=> "Distokia" ], [ 'text'=> "Caesar", 'value'=> "Caesar" ] ];
        $formOptions['calfSexOptions'] = [[ 'value'=> 'Male', 'text'=> 'Male' ],[ 'value'=> 'Female', 'text'=> 'Female']];
        $formOptions['calfBreedOptions'] = FmsUtil::toOptions( FmsUtil::getBreeds(), 'breed', 'breed', false ) ;

        $formOptions['successPartusOptions'] = [
            ['text'=>'Yes', 'value'=>true],
            ['text'=>'No', 'value'=>false],
        ];

        return parent::setupFormOptions($formOptions, $data); // TODO: Change the autogenerated stub
    }


    public function afterSave($data)
    {
        $now = Carbon::now(env('DEFAULT_TIME_ZONE'));
        FmsUtil::updatePregnant($data['farmNo'], $data['cattleId'], false, false, $data ,$now);
        FmsUtil::updatePartus($data['farmNo'], $data['cattleId'], true, $data ,$now);
        return parent::afterSave($data); // TODO: Change the autogenerated stub
    }

    public function afterUpdate($id, $data = null)
    {
        $now = Carbon::now(env('DEFAULT_TIME_ZONE'));
        //FmsUtil::updatePregnant($data['farmNo'], $data['cattleId'], false, false ,$data ,$now);
        //FmsUtil::updatePartus($data['farmNo'], $data['cattleId'], true, $data ,$now);
        return parent::afterUpdate($id, $data); // TODO: Change the autogenerated stub
    }


    public function additionalQuery($model, Request $request)
    {
        if(AuthUtil::isAdmin() || AuthUtil::is('owner')){
            $model = $model->where('masterId','=', Auth::user()->_id );
        }
        if( AuthUtil::is('field-officer') || AuthUtil::is('farm-admin')){
            if( isset(Auth::user()->bizUnitId) ){
                $model = $model->where('farmId','=', Auth::user()->bizUnitId );
            }else if(isset(Auth::user()->masterId) ){
                $model = $model->where('masterId','=', Auth::user()->masterId );
            }else{
                $model = $model->where('masterId','=', Auth::user()->_id );
            }
        }

        $model = $model->orderBy('checkDate', 'desc');

        return parent::additionalQuery($model, $request); // TODO: Change the autogenerated stub
    }


    public function beforeUpdateForm($population)
    {
        return parent::beforeUpdateForm($population); // TODO: Change the autogenerated stub
    }

    public function beforeUpdate($id, $data)
    {

        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }

    public function beforeSave($data)
    {

        return parent::beforeSave($data); // TODO: Change the autogenerated stub
    }


    public function getParam()
    {

        $this->def_param['farmId'] = Auth::user()->bizUnitId ?? '';
        $this->def_param['officerId'] = Auth::user()->_id;
        $this->def_param['officerName'] = Auth::user()->name;
        $this->def_param['checkDate'] = date('Y-m-d H:i:s', time());

        if(AuthUtil::is('owner')){
            $selFarms = Farm::where('masterId','=',Auth::user()->_id)->first();
            $farmId = $selFarms->_id;
        }else{
            $farmId = Auth::user()->bizUnitId;
        }

        if(AuthUtil::isAdmin()){
            $selFarms = Farm::orderBy('farmNo','asc')->first();
            $farmId = $selFarms->_id;
        }

        $this->def_param['farmObject'] = FmsUtil::getFarmObject( $farmId );

        return parent::getParam(); // TODO: Change the autogenerated stub
    }

    public function postIndex(Request $request)
    {

        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    protected function rowPostProcess($row)
    {

        return parent::rowPostProcess($row);
    }

}
