<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Workflow\Admin;

use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Sms\CallCode;
use App\Models\Sms\CoyCode;
use App\Models\Sms\Doc;
use App\Models\Core\Mongo\Sequence;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class SequenceController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'views/dms/admin/sequence';
        $this->yml_file = 'fields';

        $this->entity = 'Sequence';

        $this->model = new Sequence();
    }

    public function getIndex()
    {
        $this->title = '<img src="'.url('images/icons/yellow-file.png').'" /> Doc Sequence';

        $cname = substr(strrchr(get_class($this), '\\'), 1);

        $this->controller_name = str_replace('Controller', '', $cname);

        $this->nav_section = 'assets';

        /* YML for custom form layout */
        //$this->yml_layout_file = 'layout';

        /* YML for custom page navigation */
        //$this->nav_file = 'nav';
        //$this->nav_path = 'views/clinic/patient';

        $this->template_var = [ 'hasSideNav'=>true ];

        $this->data_url = 'dms/admin/sequence';

        $this->add_url = 'dms/admin/sequence/add';

        $this->update_url = 'dms/admin/sequence/edit';

        $this->item_data_url = 'dms/admin/sequence/data';

        $this->param_url = 'dms/admin/sequence/param';

        $this->del_url = 'dms/admin/sequence/del';

        $this->clone_url = 'dms/admin/sequence/clone';

        $this->download_url = 'dms/admin/sequence/dlxl';

        $this->can_add = false;

        $this->can_upload = false;

        $this->can_download_xls = false;

        $this->can_download_csv = false;

        $this->show_print_button = false;

        $this->import_commit_url = 'dms/admin/sequence/commit';

        $this->logo = env('APP_LOGO');

        $this->show_title = true;

        $this->viewer_layout = 'form.view_layout';

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'dms.admin.sequence.formlayout';
        $this->form_dialog_size = '';

        $this->table_slot_view = 'dms.admin.sequence.table_slot';
        $this->table_head_slot_view = 'dms.admin.sequence.table_head_slot';
        $this->table_action_view = 'dms.admin.sequence.table_action';
        $this->table_modal_view = 'dms.admin.sequence.table_modal';

        $this->table_methods_view = 'dms.admin.sequence.table_methods';
        $this->table_computed_view = 'dms.admin.sequence.table_computed';
        $this->table_watch_view = 'dms.admin.sequence.table_watch';


        $this->add_methods_view = 'dms.admin.sequence.add_methods';
        $this->add_computed_view = 'dms.admin.sequence.add_computed';
        $this->add_watch_view = 'dms.admin.sequence.add_watch';

        $this->edit_methods_view = 'dms.admin.sequence.edit_methods';
        $this->edit_computed_view = 'dms.admin.sequence.edit_computed';
        $this->edit_watch_view = 'dms.admin.sequence.edit_watch';


        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $formOptions['labelTemplate'] = '`'.file_get_contents( resource_path('views/dms/admin/sequence/labeltemplate.html') ).'`';
        $formOptions['printTemplate'] = '`'.file_get_contents( resource_path('views/dms/admin/sequence/printtemplate.html') ).'`';
        $formOptions['printLabelData'] = "``";

        $this->aux_data = $formOptions;

        return parent::getIndex();
    }

    public function postIndex(Request $request)
    {
        $this->defOrderField = 'IODate';
        $this->defOrderDir = 'desc';
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {
        return response()->json(
            [
                'Status'=>'Active'
            ]

        );

    }


    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        return parent::beforeSave($data);
    }

    protected function rowPostProcess($row)
    {
        /* modify or add new fields */
        $row['name'] = $row['_id'];
        $row['padded'] = str_pad($row['seq'], env('NUM_PAD', 5), '0', STR_PAD_LEFT ) ;

        return parent::rowPostProcess($row);
    }

    public function beforeImportCommit($data)
    {
//        $data['IODate'] = ImportUtil::excelDateToNormal($data['IODate']);
//        $data['DocDate'] = ImportUtil::excelDateToNormal($data['DocDate']);
//        $data['RetDate'] = ImportUtil::excelDateToNormal($data['RetDate']);
//        $data['DispDate'] = ImportUtil::excelDateToNormal($data['DispDate']);

        return parent::beforeImportCommit($data); // TODO: Change the autogenerated stub
    }


}
