-
    name: _id
    type: object
    default: ''
    nullable: true
    api:
        show: false
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: ajax
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: handle
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: deleted
    type: integer
    default: 0
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: createdAt
    type: datetime
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: updatedAt
    type: datetime
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: updated_at
    type: datetime
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: created_at
    type: datetime
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: ownerId
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: ownerName
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: picture
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: pictureObjects
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: category
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: categoryCode
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: slug
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: locationName
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: description
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false
-
    name: specifications
    type: string
    default: ''
    nullable: true
    api:
        show: true
        create: true
        edit: true
        view: true
        validator: ''
        default: ''
        transform: false