
{!! $taskId ?? '' !!}
{!! $taskName ?? '' !!}
{!! $taskDescription ?? '' !!}
{!! $taskGuide ?? '' !!}
{!! $taskAttachments ?? '' !!}
{!! $projectId ?? '' !!}
{!! $projectName ?? '' !!}
{!! $progressStatus ?? '' !!}
{!! $assignedTo ?? '' !!}
{!! $kanbanLane ?? '' !!}
{!! $startDateTime ?? '' !!}
{!! $endDateTime ?? '' !!}
{!! $duration ?? '' !!}
{!! $tz ?? '' !!}
{!! $event ?? '' !!}
{!! $attStatus ?? '' !!}
{!! $clockIn ?? '' !!}
{!! $clockOut ?? '' !!}
{!! $atBreak ?? '' !!}
{!! $clockInTime ?? '' !!}
{!! $clockOutTime ?? '' !!}
{!! $timerVal ?? '' !!}
{!! $timerSec ?? '' !!}
{!! $timerRunning ?? '' !!}
{!! $user ?? '' !!}
{!! $userId ?? '' !!}
{!! $userName ?? '' !!}