<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Core;

use App\Helpers\AuthUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Core\Mongo\APILog;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ApiLogController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

//        $this->res_path = 'views/core/apilog';
//        $this->yml_file = 'fields';

        $this->res_path = 'models/controllers/core';
        $this->yml_file = 'apilog_controller';

        $this->entity = 'API Log';


        $this->auth_entity = 'api-log';


        $this->controller_base = 'api-log';


        $this->view_base = 'core.apilog';

        $this->model = new APILog();
    }

    /**
     * @hideFromAPIDocumentation
     * @return mixed
     */
    public function getIndex()
    {
        $this->title = 'API Log';

        $cname = substr(strrchr(get_class($this), '\\'), 1);

        $this->controller_name = str_replace('Controller', '', $cname);

        $this->logo = env('APP_LOGO');

        $this->show_title = true;

        $this->viewer_layout = 'core.apilog.formlayout';

        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'core.apilog.formlayout';
        $this->form_dialog_size = 'xl';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();


        $this->can_add = false;
        $this->can_update = false;
        $this->can_multi_delete = false;
        $this->can_multi_clone = false;
        $this->can_revise = false;
        $this->can_upload = false;
        $this->can_clone = false;
        $this->can_delete = false;
        $this->can_print = false;

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $this->aux_data = $formOptions;

        $this->view_title_fields = '"View Log " + " " +this.created_at ' ;

        return parent::getIndex();
    }

    public function beforeUpdateForm($population)
    {
        //$population['request_data'] = json_encode($population['request_data']);
        //$population['response_data'] = json_encode($population['response_data']);
        return parent::beforeUpdateForm($population); // TODO: Change the autogenerated stub
    }


    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        return $model;
    }

    protected function rowPostProcess($row)
    {
        /* modify or add new fields */
        //$row['linkConsult'] = url('clinic/patient/km/'.$row['_id']);
        //$row['linkOp'] = url('clinic/patient/op/'.$row['_id']);

        return parent::rowPostProcess($row);
    }

}
