<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Core;

use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Dms\CallCode;
use App\Models\Dms\Doc;
use App\Models\Core\Mongo\Setting;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class SettingController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'views/core/setting';
        $this->yml_file = 'fields';

        $this->entity = 'Section';

        $this->table_grouped = true;

        $this->model = new Setting();
    }

    public function getIndex()
    {
        $this->title = '<img src="'.url('images/icons/yellow-file.png').'" /> System Settings';

        $cname = substr(strrchr(get_class($this), '\\'), 1);

        $this->controller_name = str_replace('Controller', '', $cname);

        $this->nav_section = 'assets';

        /* YML for custom form layout */
        //$this->yml_layout_file = 'layout';

        /* YML for custom page navigation */
        //$this->nav_file = 'nav';
        //$this->nav_path = 'views/clinic/patient';

        $this->template_var = [ 'hasSideNav'=>true ];

        $this->data_url = 'sys/setting';

        $this->add_url = 'sys/setting/add';

        $this->update_url = 'sys/setting/edit';

        $this->item_data_url = 'sys/setting/data';

        $this->param_url = 'sys/setting/param';

        $this->del_url = 'sys/setting/del';

        $this->clone_url = 'sys/setting/clone';

        $this->download_url = 'sys/setting/dlxl';

        $this->can_add = true;

        $this->can_upload = true;

        $this->can_download_xls = true;

        $this->can_download_csv = true;

        $this->import_commit_url = 'sys/setting/commit';

        $this->logo = env('APP_LOGO');

        $this->show_title = true;

        $this->viewer_layout = 'form.view_layout';

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'core.setting.formlayout';
        $this->form_dialog_size = '';

        $this->table_slot_view = 'core.setting.table_slot';
        $this->table_head_slot_view = 'core.setting.table_head_slot';
        $this->table_action_view = 'core.setting.table_action';
        $this->table_modal_view = 'core.setting.table_modal';

        $this->table_methods_view = 'core.setting.table_methods';
        $this->table_computed_view = 'core.setting.table_computed';
        $this->table_watch_view = 'core.setting.table_watch';


        $this->add_methods_view = 'core.setting.add_methods';
        $this->add_computed_view = 'core.setting.add_computed';
        $this->add_watch_view = 'core.setting.add_watch';

        $this->edit_methods_view = 'core.setting.edit_methods';
        $this->edit_computed_view = 'core.setting.edit_computed';
        $this->edit_watch_view = 'core.setting.edit_watch';

        $this->table_grouped = true;

        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $formOptions['labelTemplate'] = '`'.file_get_contents( resource_path('views/core/setting/labeltemplate.html') ).'`';
        $formOptions['printTemplate'] = '`'.file_get_contents( resource_path('views/core/setting/printtemplate.html') ).'`';
        $formOptions['printLabelData'] = "``";

        $this->aux_data = $formOptions;

        return parent::getIndex();
    }

    public function postIndex(Request $request)
    {
        $this->defOrderField = 'IODate';
        $this->defOrderDir = 'desc';
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {
        return response()->json(
            [
                'Status'=>'Active'
            ]

        );

    }

    public function externalData($data, $request)
    {
        $temp = [];

        for($i = 0; $i < count($data); $i++ ){
            $temp[ $data[$i]['section'] ][] = $data[$i];
        }

        $out = [];
        foreach($temp as $k=>$v){
            $out[] = [
                'label'=>$k,
                'mode'=>'span',
                'children'=>$v
            ];
        }

        return $out;

    }


    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        return parent::beforeSave($data);
    }

    protected function rowPostProcess($row)
    {
        /* modify or add new fields */
        //$row['linkConsult'] = url('clinic/patient/km/'.$row['_id']);
        //$row['linkOp'] = url('clinic/patient/op/'.$row['_id']);

        return parent::rowPostProcess($row);
    }

    public function beforeImportCommit($data)
    {
//        $data['IODate'] = ImportUtil::excelDateToNormal($data['IODate']);
//        $data['DocDate'] = ImportUtil::excelDateToNormal($data['DocDate']);
//        $data['RetDate'] = ImportUtil::excelDateToNormal($data['RetDate']);
//        $data['DispDate'] = ImportUtil::excelDateToNormal($data['DispDate']);

        return parent::beforeImportCommit($data); // TODO: Change the autogenerated stub
    }


}
