<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Reference;

use App\Helpers\App\DmsUtil;
use App\Helpers\Injector;
use App\Helpers\App\SalesopUtil;
use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Core\Mongo\User;
use App\Models\Reference\Currency;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class CurrencyController extends AdminController

{
    public function __construct()
    {
        parent::__construct();


        $this->res_path = 'models/controllers/reference';
        $this->yml_file = 'currency_controller';

        $this->entity = 'Currency';
        $this->auth_entity = 'currency';

        $this->controller_base = 'reference/currency';

        $this->view_base = 'reference.currency';

        $this->model = new Currency();
    }

    public function getIndex()
    {
        $this->title = 'Currency';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);

        $this->logo = env('APP_LOGO');
        $this->show_title = true;

        $this->viewer_layout = 'reference.currency.formlayout';
        $this->viewer_dialog_size = 'md';

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'reference.currency.formlayout';
        $this->form_dialog_size = 'md';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        // $this->aux_data = array_merge( $uiOptions ,$formOptions);

        $this->add_title_fields = sprintf('"%s<div style=\"float: right;padding-left: 8px;\"><h4 style=\"margin-bottom: 0px;\">"+ "Add : Currency" + "</h4></div>"',  '<img src=\"'.url('images/icons/purchasereq.png').'\" style=\"width:50px;height:auto;\" />' );
        $this->view_title_fields = sprintf('"%s<div style=\"float: right;padding-left: 8px;\"><h4 style=\"margin-bottom: 0px;\">View "+ this.name + "</h4></div>"',  '<img src=\"'.url('images/icons/purchasereq.png').'\" style=\"width:50px;height:auto;\"/>' );
        $this->update_title_fields = sprintf('"<h4>%s Update "  + this.name + "</h4>"',  '<img src=\"'.url('images/icons/purchasereq.png').'\" style=\"width:50px;height:auto;\"/>' );


        return parent::getIndex();
    }

    public function postIndex(Request $request)
    {

        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function additionalQuery($model, Request $request)
    {

        return $model;
    }

    public function beforeSave($data)
    {

        return parent::beforeSave($data);
    }

    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }


    protected function rowPostProcess($row)
    {


        return parent::rowPostProcess($row);
    }

    public function beforeImportCommit($data)
    {


        return parent::beforeImportCommit($data); // TODO: Change the autogenerated stub
    }


}
