<?php
/**
 * Created by VSCode.
 * User: mfaiza
 * Date: 16/03/21
 * Time: 12.30
 */

namespace App\Http\Controllers\Reference;

use App\Helpers\App\DmsUtil;
use App\Helpers\Injector;
use App\Helpers\App\SalesopUtil;
use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Core\Mongo\User;
use App\Models\Reference\Scope;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ScopeController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/reference';
        $this->yml_file = 'scope_controller';

        $this->entity = 'Scope';
        $this->auth_entity = 'Scope';

        $this->controller_base = 'reference/scope';

        $this->view_base = 'reference.scope';

        $this->model = new Scope();
    }

    public function getIndex()
    {
        $this->title = 'Scope';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);

        $this->logo = env('APP_LOGO');
        $this->show_title = true;

        $this->viewer_layout = 'reference.scope.formlayout';
        $this->viewer_dialog_size = 'lg';

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'reference.scope.formlayout';
        $this->form_dialog_size = 'lg';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();


        $this->add_title_fields = sprintf('"%s<div style=\"float: right;padding-left: 8px;\"><h4 style=\"margin-bottom: 0px;\">"+ "Add : scope" + "</h4></div>"',  '<img src=\"'.url('images/icons/purchasereq.png').'\" style=\"width:50px;height:auto;\" />' );
        $this->view_title_fields = sprintf('"%s<div style=\"float: right;padding-left: 8px;\"><h4 style=\"margin-bottom: 0px;\">View "+ this.name + "</h4></div>"',  '<img src=\"'.url('images/icons/purchasereq.png').'\" style=\"width:50px;height:auto;\"/>' );
        $this->update_title_fields = sprintf('"<h4>%s Update "  + this.name + "</h4>"',  '<img src=\"'.url('images/icons/purchasereq.png').'\" style=\"width:50px;height:auto;\"/>' );

        $this->defOrderField = 'statusGroup';
        $this->defOrderDir = 'asc';

        return parent::getIndex();
    }

    public function postIndex(Request $request)
    {

        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function additionalQuery($model, Request $request)
    {
        $model = $model->orderBy('statusGroup','asc')->orderBy('seq','asc');

        return $model;
    }

    public function beforeSave($data)
    {

        return parent::beforeSave($data);
    }

    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }


    protected function rowPostProcess($row)
    {


        return parent::rowPostProcess($row);
    }

    public function beforeImportCommit($data)
    {


        return parent::beforeImportCommit($data); // TODO: Change the autogenerated stub
    }


}
