<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Dwf\Admin;

use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Http\Controllers\Core\AdminController;
use App\Models\Dwf\CallCode;
use App\Models\Dwf\CoyCode;
use App\Models\Dwf\Doc;
use App\Models\Dwf\DocLocation;
use App\Models\Core\Mongo\Sequence;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BoxController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

//        $this->res_path = 'views/dwf/admin/box';
//        $this->yml_file = 'fields';

        $this->res_path = 'models/controllers/dwf/admin';
        $this->yml_file = 'box_controller';

        $this->entity = 'Box';

        $this->model = new DocLocation();
    }

    public function getIndex()
    {
        $this->title = '<img src="'.url('images/icons/yellow-file.png').'" /> Box';

        $cname = substr(strrchr(get_class($this), '\\'), 1);

        $this->controller_name = str_replace('Controller', '', $cname);

        $this->nav_section = 'assets';

        /* YML for custom form layout */
        //$this->yml_layout_file = 'layout';

        /* YML for custom page navigation */
        //$this->nav_file = 'nav';
        //$this->nav_path = 'views/clinic/patient';

        $this->template_var = [ 'hasSideNav'=>true ];

        $this->data_url = 'dwf/admin/box';

        $this->add_url = 'dwf/admin/box/add';

        $this->update_url = 'dwf/admin/box/edit';

        $this->item_data_url = 'dwf/admin/box/data';

        $this->param_url = 'dwf/admin/box/param';

        $this->del_url = 'dwf/admin/box/del';

        $this->clone_url = 'dwf/admin/box/clone';

        $this->download_url = 'dwf/admin/box/dlxl';

        $this->can_add = true;

        $this->can_upload = true;

        $this->can_download_xls = true;

        $this->can_download_csv = true;

        $this->show_print_button = true;

        $this->import_commit_url = 'dwf/admin/box/commit';

        $this->logo = env('APP_LOGO');

        $this->show_title = true;

        $this->viewer_layout = 'dwf.admin.box.formlayout';
        $this->viewer_dialog_size = 'md';

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'dwf.admin.box.formlayout';
        $this->form_dialog_size = 'md';

        $this->table_slot_view = 'dwf.admin.box.table_slot';
        $this->table_head_slot_view = 'dwf.admin.box.table_head_slot';
        $this->table_action_view = 'dwf.admin.box.table_action';
        $this->table_modal_view = 'dwf.admin.box.table_modal';

        $this->table_methods_view = 'dwf.admin.box.table_methods';
        $this->table_computed_view = 'dwf.admin.box.table_computed';
        $this->table_watch_view = 'dwf.admin.box.table_watch';


        $this->add_methods_view = 'dwf.admin.box.add_methods';
        $this->add_computed_view = 'dwf.admin.box.add_computed';
        $this->add_watch_view = 'dwf.admin.box.add_watch';

        $this->edit_methods_view = 'dwf.admin.box.edit_methods';
        $this->edit_computed_view = 'dwf.admin.box.edit_computed';
        $this->edit_watch_view = 'dwf.admin.box.edit_watch';


        $formOptions = Util::loadResYaml($this->yml_file,$this->res_path)->toFormOption();

        $formOptions['labelTemplate'] = '`'.file_get_contents( resource_path('views/dwf/admin/box/labeltemplate.html') ).'`';
        $formOptions['printTemplate'] = '`'.file_get_contents( resource_path('views/dwf/admin/box/printtemplate.html') ).'`';
        $formOptions['printLabelData'] = "``";

        $this->aux_data = $formOptions;

        return parent::getIndex();
    }

    public function postIndex(Request $request)
    {
        $this->defOrderField = 'IODate';
        $this->defOrderDir = 'desc';
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {
        return response()->json(
            [
                'Status'=>'Active'
            ]

        );

    }


    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );
        return $model;
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        return parent::beforeSave($data);
    }

    protected function rowPostProcess($row)
    {
        /* modify or add new fields */

        return parent::rowPostProcess($row);
    }

    public function beforeImportCommit($data)
    {
//        $data['IODate'] = ImportUtil::excelDateToNormal($data['IODate']);
//        $data['DocDate'] = ImportUtil::excelDateToNormal($data['DocDate']);
//        $data['RetDate'] = ImportUtil::excelDateToNormal($data['RetDate']);
//        $data['DispDate'] = ImportUtil::excelDateToNormal($data['DispDate']);

        return parent::beforeImportCommit($data); // TODO: Change the autogenerated stub
    }


}
