<?php
namespace App\Http\Controllers\Api\Core;

use App\Helpers\APIUtil;
use App\Helpers\AuthUtil;
use App\Helpers\Util;
use App\Http\Controllers\Api\Core\ApiAdminController;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends ApiAdminController
{

    public function __construct()
    {
        $this->controller_name = strtolower( str_replace('Controller', '', get_class()) );
        $this->model = new User();

        $this->res_path = 'models'; // under resources ,ie: resources/models
        $this->yml_file = 'user'; // name of yml ,ie: member.yml
        $this->entity = 'User';

    }

    public function postAdd(Request $request)
    {
        $uEmail = false;
        $uMobile = false;
        $uString = '';

        if( $this->isExists($this->model, 'email', $request->get('email'))){
            $uString = 'Email';
            $uEmail = true;
        }

        if( $this->isExists($this->model, 'mobile', $request->get('mobile'))){
            if($uString != ''){
                $uString .= ' & Mobile';
            }else{
                $uString = 'Mobile';
            }
            $uMobile = true;
        }

        if( $uEmail || $uMobile){
            $retVal = array("result" => "ERR", "message" => $uString." already used","data"=>$request->get('email') );
            return response()->json($retVal, 415);
        }

        return parent::postAdd($request); // TODO: Change the autogenerated stub
    }


    public function beforeOutput($data)
    {
        unset($data['password']);
        $data['roleId'] = AuthUtil::getRoleId( $data['roleName'] ?? env('DEFAULT_USER_ROLE', 'Penerbit' )  );
        $data['roleSlug'] = AuthUtil::getRoleSlug( $data['roleId'] );
        return parent::beforeOutput($data); // TODO: Change the autogenerated stub
    }


    public function beforeSave($data)
    {
        $roleName = $data['roleName'] ?? env('DEFAULT_USER_ROLE', 'Penerbit' );
        $data['roleName'] = $roleName;
        $data['roleId'] = AuthUtil::getRoleId($roleName);
        $data['roleSlug'] = AuthUtil::getRoleSlug( $data['roleId'] );
        $data['roleName'] = AuthUtil::getRoleName($data['roleId']);
        if(isset($data['password'])){
            $data['password'] = Hash::make($data['password']);
        }
        $data['memberReferralCode'] = $data['memberReferralCode'] ?? strtoupper( Util::randomstring(8, 'alphanumeric'));
        $data['regStatus'] = env('DEFAULT_REG_STATUS', 'UNASSIGNED');
        $data = APIUtil::addGeoLocation($data);
        return parent::beforeSave($data); // TODO: Change the autogenerated stub
    }

    public function afterSave($data)
    {
        //$data->afterSave = 'AFTER';
        return parent::afterSave($data); // TODO: Change the autogenerated stub
    }

    public function beforeUpdate($data)
    {
        $roleName = $data['roleName'] ?? env('DEFAULT_USER_ROLE', 'Penerbit' );
        $data['roleName'] = $roleName;
        $data['roleId'] = AuthUtil::getRoleId($roleName);
        $data['roleSlug'] = AuthUtil::getRoleSlug( $data['roleId'] );
        $data['roleName'] = AuthUtil::getRoleName($data['roleId']);
        if(isset($data['password']) && $data['password'] != ''){
            $data['password'] = Hash::make($data['password']);
        }
        $data['memberReferralCode'] = $data['memberReferralCode'] ?? strtoupper( Util::randomstring(8, 'alphanumeric'));

        $data = APIUtil::addGeoLocation($data);
        return parent::beforeUpdate($data); // TODO: Change the autogenerated stub
    }

}
