<?php
/**
 * Created by PhpStorm.
 * User: awidarto
 * Date: 13/12/19
 * Time: 23.33
 */
namespace App\Http\Controllers\Halal;

use App\Helpers\AuthUtil;
use App\Helpers\ImportUtil;
use App\Helpers\Util;
use App\Helpers\RefUtil;
use App\Helpers\Injector;
use App\Http\Controllers\Core\AdminController;
use App\Models\Halal\HalalProduct;
use App\Models\Halal\BizProfile;
use App\Models\Core\Mongo\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Auth;

class HalalProductController extends AdminController

{
    public function __construct()
    {
        parent::__construct();

        $this->res_path = 'models/controllers/halal';

        $this->yml_file = 'halalproduct_controller';

        $this->entity = 'Halal Product';

        $this->auth_entity = 'halal-product';

        $this->controller_base = 'halal/halal-product';

        $this->view_base = 'halal.halalproduct';

        $this->model = new HalalProduct();
    }

    public function getIndex()
    {
        $this->title = 'Halal Product';

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
        * Set form layout
        */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'halal.halalproduct.form_layout';
        $this->form_dialog_size = 'lg';

        /**
        * Set Viewer layout
        */
        $this->viewer_layout = 'halal.halalproduct.view_layout';
        $this->viewer_dialog_size = 'lg';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->add_as_page = false;
        $this->edit_as_page = false;
        $this->with_advanced_search = false;
        $this->update_title_fields = '"<h4>'.__('Ubah')." ".'" + this.name + "</h4>"';
        $this->view_title_fields = '"<h4>'.__('Lihat')." ".'" + this.name + "</h4>"';

        $this->add_filler = false;

        return parent::getIndex();
    }

    public function getList(Request $request, $keyword0, $keyword1 = null, $keyword2 = null)
    {
        $this->title = __('Halal Product').' : '.__(Str::headline($keyword0));

        $cname = substr(strrchr(get_class($this), '\\'), 1);
        $this->controller_name = str_replace('Controller', '', $cname);
        $this->show_title = true;
        /**
         * Set form layout
         */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'halal.halalproduct.form_layout';
        $this->form_dialog_size = 'xl';

        /**
         * Set Viewer layout
         */
        $this->viewer_layout = 'halal.halalproduct.view_layout';
        $this->viewer_dialog_size = 'xl';

        $this->runAcl();
        $this->runUrlSet();
        $this->runViewSet();
        $this->runMoreMenu();

        $this->add_as_page = false;
        $this->edit_as_page = false;
        $this->with_advanced_search = false;
        $this->update_title_fields = '"<h4>'.__('Ubah')." ".'" + this.name + "</h4>"';
        $this->view_title_fields = '"<h4>'.__('Lihat')." ".'" + this.name + "</h4>"';

        $this->add_filler = false;

        return parent::getList($request, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }


    public function setupInjector($uiOptions, $data = null)
    {
        /**
         * BOM
         *
         * field name : bom
         *
         * sub fields :
         * Nama Bahan | material
         * Merek Produk | materialBrand
         * Produsen | producer
         * Nomor Sertifikat Halal | halalCertNo
         * Masa Berlaku Sertifikasi Halal | halalCertValidUntil
         */

        $uiOptions = Injector::setObject('bom') // name variable / field yang akan diinject
        ->setObjFields( // mwnambahkan setting field untuk table
            [
                [ 'label'=>'Nama Bahan', 'key'=>'material', 'class'=>'text-100' , 'type'=>'String' , 'validator'=>'required'  ],
                [ 'label'=>'Merek Produk', 'key'=>'materialBrand', 'class'=>'text-200', 'type'=>'String', 'validator'=>'required'  ],
                [ 'label'=>'Produsen', 'key'=>'producer', 'class'=>'text-150', 'type'=>'String' , 'validator'=>''  ],
                [ 'label'=>'Nomor Sertifikat Halal', 'key'=>'halalCertNo', 'class'=>'text-75 text-center', 'type'=>'string', 'validator'=>'required'  ],
                [ 'label'=>'Masa Berlaku Sertifikasi Halal', 'key'=>'halalCertValidUntil', 'class'=>'text-75 text-center', 'type'=>'String' , 'validator'=>'required'  ]
            ]
        )->setObjDef( // set object default
            [
                'material'=>'',
                'materialBrand'=>'',
                'producer'=>'',
                'halalCertNo'=> '',
                'halalCertValidUntil'=>''
            ]
        )->setObjParams(
            [
                // 'uom' => $formOptions['uomOptions'] = RefUtil::toOptions(RefUtil::getUom(),'uom','uom', false),
            ]
        )
        ->setObjTemplate(view('halal.halalproduct.bom')->render()) // set template
        ->injectObject($uiOptions);

        return parent::setupInjector($uiOptions, $data); // TODO: Change the autogenerated stub
    }

    public function setupFormOptions($formOptions, $data = null)
    {

        $formOptions['productStatusOptions'] = [[ 'value'=> 'Belum Tersertifikasi', 'text'=> 'Belum Tersertifikasi' ],[ 'value'=> 'Dalam Proses', 'text'=> 'Dalam Proses'],[ 'value'=> 'Tersertifikasi Halal', 'text'=> 'Tersertifikasi Halal']];


        $formOptions['businessRefOptions'] = RefUtil::toOptions(RefUtil::getBizBusiness(),'bizRegisteredName','bizRegisteredName', false);

        return parent::setupFormOptions($formOptions, $data); // TODO: Change the autogenerated stub
    }

    public function getAdd(Request $request, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        $this->title = __('Add').' '.$this->entity;

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'halal.halalproduct.form_layout';

        $this->runAcl();
        $this->runUrlSet('add');
        $this->runPageViewSet('add');

        $uiOptions = [];

        $uiOptions = $this->setupInjector($uiOptions);

        $formOptions = Util::loadResYaml($this->yml_file, $this->res_path)->toFormOption();

        $formOptions = $this->setupFormOptions($formOptions);

        $this->aux_data = array_merge( $uiOptions ,$formOptions);

        $this->page_redirect_after_save = true;

        // $this->page_class = 'col-lg-8 col-md-10 col-xs-12';

        return parent::getAdd($request, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function getEdit(Request $request, $id, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        $item = $this->model->find($id);

        $this->item_id = $item->_id;

        $this->title = __('Edit').' '.$item->name;

        /* Use custom form layout */
        $this->form_view = 'form.html'; // use plain html
        $this->form_layout = 'halal.halalproduct.form_layout';

        $this->runAcl();
        $this->runUrlSet('edit');
        $this->runPageViewSet('edit');

        $uiOptions = [];

        $uiOptions = $this->setupInjector($uiOptions);

        $formOptions = Util::loadResYaml($this->yml_file, $this->res_path)->toFormOption();

        $formOptions = $this->setupFormOptions($formOptions);

        $this->aux_data = array_merge( $uiOptions ,$formOptions);

        $this->page_redirect_after_save = true;

        $this->page_class = 'col-lg-6 col-md-10 col-xs-12';

        return parent::getEdit($request, $id, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function getView(Request $request, $id, $keyword0 = null, $keyword1 = null, $keyword2 = null)
    {
        return parent::getView($request, $id, $keyword0, $keyword1, $keyword2); // TODO: Change the autogenerated stub
    }

    public function postClone(Request $request)
    {
        $this->revision_key = 'requestNo';
        return parent::postClone($request);
    }

    public function postIndex(Request $request)
    {
//        $this->defOrderField = 'Item';
//        $this->defOrderDir = 'asc';
        return parent::postIndex($request); // TODO: Change the autogenerated stub
    }

    public function additionalQuery($model, Request $request)
    {
        /* sample query modifier */
        //$model = $model->where('roleId','=', AuthUtil::getRoleId('Employee') );

        if($request->has('keywords')){
            $k = $request->get('keywords');
            if($k['keyword0'] == 'not-certified'){
                $model = $model->where('productStatus','=', 'Belum Tersertifikasi' );
            }
        }

        if($request->has('keywords')){
            $k = $request->get('keywords');
            if($k['keyword0'] == 'in-progress'){
                $model = $model->where('productStatus','=', 'Dalam Proses' );
            }
        }

        if($request->has('keywords')){
            $k = $request->get('keywords');
            if($k['keyword0'] == 'certified'){
                $model = $model->where('productStatus','=', 'Tersertifikasi Halal' );
            }
        }

        return parent::additionalQuery($model, $request); // TODO: Change the autogenerated stub
    }

    public function beforeSave($data)
    {
        /* sample callback / hook */
        //$data['roleId'] = AuthUtil::getRoleId('Employee');
        $data['sihalal_status'] = "false";
        return parent::beforeSave($data);
    }

    public function beforeUpdateForm($population)
    {
        return parent::beforeUpdateForm($population); // TODO: Change the autogenerated stub
    }

    public function beforeUpdate($id, $data)
    {

        return parent::beforeUpdate($id, $data); // TODO: Change the autogenerated stub
    }

    public function getParam()
    {

        return parent::getParam(); // TODO: Change the autogenerated stub
    }

    protected function rowPostProcess($row)
    {

        return parent::rowPostProcess($row);
    }

    public function postGetSeq(Request $request)
    {

        $businessRef = $request->get('businessRef');

        $trd = BizProfile::select('bizTradeMark')
            ->where('bizRegisteredName', '=', $businessRef)
            ->get();
        $trade = $trd->each->makeHidden(['_id']);


        if($trade){
            return response()->json([
                'result'=>'OK',
                'tradeMark'=>$trade
            ]);

        }else{
            return response()->json([
                'result'=>'ERR',
                'msg'=>'NOENTITY'
            ]);
        }


    }

    public function regHalal(Request $request){

        // $acak = rand(0,1000);
        $mail = Auth::user()->email;
        $name = Auth::user()->name;
        $password = "temanQu2022";

        $sihalal = Http::post('http://dev-api.halal.go.id/v1/users',[
        'email' => $mail,
        'password' => $password,
        'name'=> $name,
        'type_of_user' => 'R.10'

         ])->body();
         $result_json = json_decode($sihalal, true);
        //  print_r($result_json['data']['userid']);

        if(isset($result_json['statusCode'])){
            $userid = $result_json['data']['userid'];
            $verify_code = $result_json['data']['verify_code'];
            $verify_date = $result_json['data']['verify_date'];
            $nama = $result_json['data']['nama'];
            $email_addr = $result_json['data']['email_addr'];
            $psswd = $result_json['data']['psswd'];

            $halalresult = User::where('email', $mail)
            ->update([
                'sihalal_member' => 'true',
                'sihalal_userid' => $userid,
                'sihalal_nama' => $nama,
                'sihalal_verify_code' => $verify_code,
                'sihalal_verify_date' => $verify_date,
                'sihalal_email_addr' => $email_addr,
                'sihalal_psswd' => $psswd
            ] );

            return redirect('halal/sihalal-register2');
        }else{
            return redirect('halal/sihalal-register');
        }

    }

    public function reg2Halal(Request $request){


        $mail = Auth::user()->email;
        // $acak = rand(0,1000);
        $user_id = Auth::user()->sihalal_userid;
        $biz_id_type = Auth::user()->bizIdType;
        $biz_id_number = Auth::user()->bizIdNumber;
        $nama_pu = Auth::user()->bizRegisteredName ;
        $alamat_pu = Auth::user()->bizAddress;
        $kota_pu = Auth::user()->kota_pu;
        $prov_pu = Auth::user()->prov_pu;
        $kode_pos_pu = Auth::user()->kode_pos_pu;
        $no_telp_pu = Auth::user()->no_telp_pu;
        $jenis_usaha = Auth::user()->bizType;
        $skala_usaha = Auth::user()->skala_usaha;
        $id_prov = Auth::user()->id_prov;
        $email_perusahaan = Auth::user()->email_perusahaan;
        $modal_dasar = Auth::user()->modal_dasar;
        $nama_pj = Auth::user()->bizPicName;
        $no_kontak_pj = Auth::user()->contactWA;
        $email_pj = Auth::user()->bizPicEmail;
        $pu_aspek_legal = Auth::user()->pu_aspek_legal;
            $jenissurat = $pu_aspek_legal['0']['jenis_surat'];
            $tglsurat = $pu_aspek_legal['0']['tgl_surat'];
            $masaberlaku = $pu_aspek_legal['0']['masa_berlaku'];
            $nosurat = $pu_aspek_legal['0']['no_surat'];
            $suratlain = $pu_aspek_legal['0']['jenis_surat_lainnya'];
            $penerbit = $pu_aspek_legal['0']['instansi_penerbit'];
        $pabrik = Auth::user()->pabrik;
            $namapabrik = $pabrik['0']['nama'];
            $alamatpabrik = $pabrik['0']['alamat'];
            $kabpabrik = $pabrik['0']['kab_kota'];
            $provpabrik = $pabrik['0']['provinsi'];
            $negarapabrik = $pabrik['0']['negara'];
            $pospabrik = $pabrik['0']['kode_pos'];
            $statuspabrik = $pabrik['0']['status_milik'];
        $outlet = Auth::user()->outlet;
            $namaoutlet = $outlet['0']['nama'];
            $alamatoutlet = $outlet['0']['alamat'];
            $kaboutlet = $outlet['0']['kab_kota'];
            $provoutlet = $outlet['0']['provinsi'];
            $negaraoutlet = $outlet['0']['negara'];
            $posoutlet = $outlet['0']['kode_pos'];
        $penyelia = Auth::user()->penyelia;
            $namapenyelia = $penyelia['0']['nama'];
            $noktppenyelia = $penyelia['0']['no_ktp'];
            $nosertipenyelia = $penyelia['0']['no_sertifikat'];
            $tglsertipenyelia = $penyelia['0']['tgl_sertifikat'];
            $noskpenyelia = $penyelia['0']['no_sk'];
            $tglskpenyelia = $penyelia['0']['tgl_sk'];
            $nokontakpenyelia = $penyelia['0']['no_kontak'];
            $filektppenyelia = $penyelia['0']['file_ktp'];
            $agamapenyelia = $penyelia['0']['agama'];


        if($biz_id_type == 'NIK'){
            $sihalal = Http::post('http://dev-api.halal.go.id/v1/pu/nik',[
            'userid' => $user_id,
            'nik' =>  $biz_id_number,
            'nama_pu'=> $nama_pu,
            'alamat_pu' => $alamat_pu,
            'kota_pu' => $kota_pu,
            'prov_pu' => $prov_pu,
            'kode_pos_pu'=> $kode_pos_pu,
            'no_telp_pu' => $no_telp_pu,
            'jenis_usaha' => $jenis_usaha,
            'skala_usaha'=> $skala_usaha,
            'id_prov' => $id_prov,
            'email_perusahaan' => $email_perusahaan,
            'modal_dasar'=> $modal_dasar,
            'nama_pj' =>  $nama_pj,
            'no_kontak_pj' => $no_kontak_pj,
            'email_pj'=> $email_pj,
            'pu_aspek_legal' => [[
                'jenis_surat' => $jenissurat,
                'jenis_surat_lainnya' => $suratlain,
                'no_surat' => $nosurat,
                'tgl_surat' => '',
                'masa_berlaku' => '',
                'instansi_penerbit' => $penerbit
            ]],
            'pabrik' => [[
                'nama' => $namapabrik,
                'alamat' => $alamatpabrik,
                'kab_kota' => $kabpabrik,
                'provinsi' => $provpabrik,
                'negara' => $negarapabrik,
                'kode_pos' => $pospabrik,
                'status_milik' => $statuspabrik
            ]],
            'outlet' => [[
                    'nama' => $namaoutlet,
                    'alamat' => $alamatoutlet,
                    'kab_kota' => $kaboutlet,
                    'provinsi' => $provoutlet,
                    'negara' => $negaraoutlet,
                    'kode_pos' => $posoutlet
            ]],
            'penyelia' => [[
                    'nama' => $namapenyelia,
                    'no_ktp' => $noktppenyelia,
                    'no_sertifikat' => $nosertipenyelia,
                    'tgl_sertifikat' => '',
                    'no_sk' => $noskpenyelia,
                    'tgl_sk' => '',
                    'no_kontak' => $nokontakpenyelia,
                    'file_ktp' => $filektppenyelia,
                    'agama' => $agamapenyelia
            ]]

            ])->body();


            $result_json = json_decode($sihalal, true);
            // cara tangkap array multidimensi
            // print_r ($result_json);


            if(isset($result_json['statusCode']) && $result_json['statusCode'] == 201){

                $sihalal_id_pu = $result_json['data']['data_pu']['id_pu'];
                $sihalal_no_ndpu = $result_json['data']['data_pu']['no_ndpu'];
                $sihalal_nama_pu = $result_json['data']['data_pu']['nama_pu'];
                $sihalal_alamat_pu = $result_json['data']['data_pu']['alamat_pu'];
                $sihalal_kota_pu = $result_json['data']['data_pu']['kota_pu'];
                $sihalal_prov_pu = $result_json['data']['data_pu']['prov_pu'];
                $sihalal_negara_pu = $result_json['data']['data_pu']['negara_pu'];
                $sihalal_kode_pos_pu = $result_json['data']['data_pu']['kode_pos_pu'];
                $sihalal_email = $result_json['data']['data_pu']['email'];
                $sihalal_no_telp = $result_json['data']['data_pu']['no_telp'];
                $sihalal_jenis_usaha = $result_json['data']['data_pu']['jenis_usaha'];
                $sihalal_skala_usaha = $result_json['data']['data_pu']['skala_usaha'];
                $sihalal_nama_pim = $result_json['data']['data_pu']['nama_pim'];
                $sihalal_jabatan_pim = $result_json['data']['data_pu']['jabatan_pim'];
                $sihalal_no_kontak_pim = $result_json['data']['data_pu']['no_kontak_pim'];
                $sihalal_email_pim = $result_json['data']['data_pu']['email_pim'];
                $sihalal_nama_pj = $result_json['data']['data_pu']['nama_pj'];
                $sihalal_no_kontak_pj = $result_json['data']['data_pu']['no_kontak_pj'];
                $sihalal_email_pj = $result_json['data']['data_pu']['email_pj'];
                $sihalal_id_prov = $result_json['data']['data_pu']['id_prov'];
                $sihalal_id_negara = $result_json['data']['data_pu']['id_negara'];
                $sihalal_created_by = $result_json['data']['data_pu']['created_by'];
                $sihalal_created_on = $result_json['data']['data_pu']['created_on'];
                $sihalal_updated_by = $result_json['data']['data_pu']['updated_by'];
                $sihalal_updated_on = $result_json['data']['data_pu']['updated_on'];
                $sihalal_tgl_ndpu = $result_json['data']['data_pu']['tgl_ndpu'];
                $sihalal_no_urut_ndpu = $result_json['data']['data_pu']['no_urut_ndpu'];
                $sihalal_f_ln = $result_json['data']['data_pu']['f_ln'];
                $sihalal_f_umk = $result_json['data']['data_pu']['f_umk'];
                $sihalal_perseroan_daerah_id = $result_json['data']['data_pu']['perseroan_daerah_id'];
                $sihalal_id_pu_induk = $result_json['data']['data_pu']['id_pu_induk'];
                $sihalal_oss_id = $result_json['data']['data_pu']['oss_id'];
                $sihalal_modal_dasar = $result_json['data']['data_pu']['modal_dasar'];
                $sihalal_id_proyek = $result_json['data']['data_pu']['id_proyek'];

                $halalresult = User::where('email', $mail)
                ->update([
                    'status_sihalal_pu' => true,
                    'sihalal_id_pu '  => $sihalal_id_pu ,
                    'sihalal_no_ndpu'  => $sihalal_no_ndpu,
                    'sihalal_nama_pu ' => $sihalal_nama_pu,
                    'sihalal_alamat_pu' => $sihalal_alamat_pu,
                    'sihalal_kota_pu ' => $sihalal_kota_pu,
                    'sihalal_prov_pu ' => $sihalal_prov_pu,
                    'sihalal_negara_pu'  => $sihalal_negara_pu,
                    'sihalal_kode_pos_pu'  => $sihalal_kode_pos_pu,
                    'sihalal_email ' => $sihalal_email,
                    'sihalal_no_telp'  => $sihalal_no_telp,
                    'sihalal_jenis_usaha'  => $sihalal_jenis_usaha,
                    'sihalal_skala_usaha ' => $sihalal_skala_usaha,
                    'sihalal_nama_pim ' => $sihalal_nama_pim,
                    'sihalal_jabatan_pim'  => $sihalal_jabatan_pim,
                    'sihalal_no_kontak_pim'  => $sihalal_no_kontak_pim,
                    'sihalal_email_pim ' => $sihalal_email_pim,
                    'sihalal_nama_pj ' => $sihalal_nama_pj,
                    'sihalal_no_kontak_pj'  => $sihalal_no_kontak_pj,
                    'sihalal_email_pj ' => $sihalal_email_pj,
                    'sihalal_id_prov ' => $sihalal_id_prov,
                    'sihalal_id_negara'  => $sihalal_id_negara,
                    'sihalal_created_by'  => $sihalal_created_by,
                    'sihalal_created_on ' => $sihalal_created_on,
                    'sihalal_updated_by ' => $sihalal_updated_by,
                    'sihalal_updated_on ' => $sihalal_updated_on,
                    'sihalal_tgl_ndpu ' => $sihalal_tgl_ndpu,
                    'sihalal_no_urut_ndpu ' => $sihalal_no_urut_ndpu,
                    'sihalal_f_ln ' => $sihalal_f_ln,
                    'sihalal_f_umk ' => $sihalal_f_umk,
                    'sihalal_perseroan_daerah_id'  => $sihalal_perseroan_daerah_id,
                    'sihalal_id_pu_induk ' => $sihalal_id_pu_induk,
                    'sihalal_oss_id ' => $sihalal_oss_id,
                    'sihalal_modal_dasar'  => $sihalal_modal_dasar,
                    'sihalal_id_proyek ' => $sihalal_id_proyek
                ] );

                return redirect('halal/sihalal-confirm');
            }else{
                return redirect('halal/sihalal-register2');
            }

        }else{
            $sihalal_nib = Http::post('http://dev-api.halal.go.id/v1/pu/nib',[
                'userid' => $user_id,
                'nib' =>  $biz_id_number,
                'nama_pj' =>  $nama_pj,
                'no_kontak_pj' => $no_kontak_pj,
                'email_pj'=> $email_pj,
                'pabrik' => [[
                    'nama' => $namapabrik,
                    'alamat' => $alamatpabrik,
                    'kab_kota' => $kabpabrik,
                    'provinsi' => $provpabrik,
                    'negara' => $negarapabrik,
                    'kode_pos' => $pospabrik,
                    'status_milik' => $statuspabrik
                ]],
                'outlet' => [[
                        'nama' => $namaoutlet,
                        'alamat' => $alamatoutlet,
                        'kab_kota' => $kaboutlet,
                        'provinsi' => $provoutlet,
                        'negara' => $negaraoutlet,
                        'kode_pos' => $posoutlet
                ]],
                'penyelia' => [[
                        'nama' => $namapenyelia,
                        'no_ktp' => $noktppenyelia,
                        'no_sertifikat' => $nosertipenyelia,
                        'tgl_sertifikat' => $tglsertipenyelia,
                        'no_sk' => $noskpenyelia,
                        'tgl_sk' => $tglskpenyelia,
                        'no_kontak' => $nokontakpenyelia,
                        'file_ktp' => $filektppenyelia,
                        'agama' => $agamapenyelia
                ]]

            ])->body();


            $result_json_nib = json_decode($sihalal_nib, true);
            // cara tangkap array multidimensi
            // var_dump($result_json_nib);


            if(isset($result_json['statusCode']) && $result_json['statusCode'] == 201){

                $sihalal_nib_id_pu = $result_json['data']['data_pu']['id_pu'];
                $sihalal_nib_no_ndpu = $result_json['data']['data_pu']['no_ndpu'];
                $sihalal_nib_nama_pu = $result_json['data']['data_pu']['nama_pu'];
                $sihalal_nib_alamat_pu = $result_json['data']['data_pu']['alamat_pu'];
                $sihalal_nib_kota_pu = $result_json['data']['data_pu']['kota_pu'];
                $sihalal_nib_prov_pu = $result_json['data']['data_pu']['prov_pu'];
                $sihalal_nib_negara_pu = $result_json['data']['data_pu']['negara_pu'];
                $sihalal_nib_kode_pos_pu = $result_json['data']['data_pu']['kode_pos_pu'];
                $sihalal_nib_email = $result_json['data']['data_pu']['email'];
                $sihalal_nib_no_telp = $result_json['data']['data_pu']['no_telp'];
                $sihalal_nib_jenis_usaha = $result_json['data']['data_pu']['jenis_usaha'];
                $sihalal_nib_skala_usaha = $result_json['data']['data_pu']['skala_usaha'];
                $sihalal_nib_nama_pim = $result_json['data']['data_pu']['nama_pim'];
                $sihalal_nib_jabatan_pim = $result_json['data']['data_pu']['jabatan_pim'];
                $sihalal_nib_no_kontak_pim = $result_json['data']['data_pu']['no_kontak_pim'];
                $sihalal_nib_email_pim = $result_json['data']['data_pu']['email_pim'];
                $sihalal_nib_nama_pj = $result_json['data']['data_pu']['nama_pj'];
                $sihalal_nib_no_kontak_pj = $result_json['data']['data_pu']['no_kontak_pj'];
                $sihalal_nib_email_pj = $result_json['data']['data_pu']['email_pj'];
                $sihalal_nib_id_prov = $result_json['data']['data_pu']['id_prov'];
                $sihalal_nib_id_negara = $result_json['data']['data_pu']['id_negara'];
                $sihalal_nib_created_by = $result_json['data']['data_pu']['created_by'];
                $sihalal_nib_created_on = $result_json['data']['data_pu']['created_on'];
                $sihalal_nib_updated_by = $result_json['data']['data_pu']['updated_by'];
                $sihalal_nib_updated_on = $result_json['data']['data_pu']['updated_on'];
                $sihalal_nib_tgl_ndpu = $result_json['data']['data_pu']['tgl_ndpu'];
                $sihalal_nib_no_urut_ndpu = $result_json['data']['data_pu']['no_urut_ndpu'];
                $sihalal_nib_f_ln = $result_json['data']['data_pu']['f_ln'];
                $sihalal_nib_f_umk = $result_json['data']['data_pu']['f_umk'];
                $sihalal_nib_perseroan_daerah_id = $result_json['data']['data_pu']['perseroan_daerah_id'];
                $sihalal_nib_id_pu_induk = $result_json['data']['data_pu']['id_pu_induk'];
                $sihalal_nib_oss_id = $result_json['data']['data_pu']['oss_id'];
                $sihalal_nib_modal_dasar = $result_json['data']['data_pu']['modal_dasar'];
                $sihalal_nib_id_proyek = $result_json['data']['data_pu']['id_proyek'];

            $halalresult = User::where('email', $mail)
            ->update([
               'status_sihalal_pu' => true,
               'sihalal_id_pu' => $sihalal_nib_id_pu,
               'sihalal_no_ndpu' => $sihalal_nib_no_ndpu,
               'sihalal_nama_pu' => $sihalal_nib_nama_pu,
               'sihalal_alamat_pu' => $sihalal_nib_alamat_pu,
               'sihalal_kota_pu' => $sihalal_nib_kota_pu,
               'sihalal_prov_pu' => $sihalal_nib_prov_pu,
               'sihalal_negara_pu' => $sihalal_nib_negara_pu,
               'sihalal_kode_pos_pu' => $sihalal_nib_kode_pos_pu,
               'sihalal_email' => $sihalal_nib_email,
               'sihalal_jenis_usaha' => $sihalal_nib_jenis_usaha,
               'sihalal_skala_usaha' => $sihalal_nib_skala_usaha,
               'sihalal_nama_pim' => $sihalal_nib_nama_pim,
               'sihalal_jabatan_pim' => $sihalal_nib_jabatan_pim,
               'sihalal_no_kontak_pim' => $sihalal_nib_no_kontak_pim,
               'sihalal_email_pim' => $sihalal_nib_email_pim,
               'sihalal_nama_pj' => $sihalal_nib_nama_pj,
               'sihalal_no_kontak_pj' => $sihalal_nib_no_kontak_pj,
               'sihalal_email_pj' => $sihalal_nib_email_pj,
               'sihalal_id_prov' => $sihalal_nib_id_prov,
               'sihalal_id_negara' => $sihalal_nib_id_negara,
               'sihalal_created_by' => $sihalal_nib_created_by,
               'sihalal_created_on' => $sihalal_nib_created_on,
               'sihalal_updated_by' => $sihalal_nib_updated_by,
               'sihalal_updated_on' => $sihalal_nib_updated_on,
               'sihalal_tgl_ndpu' => $sihalal_nib_tgl_ndpu,
               'sihalal_no_urut_ndpu' => $sihalal_nib_no_urut_ndpu,
               'sihalal_f_ln' => $sihalal_nib_f_ln,
               'sihalal_f_umk' => $sihalal_nib_f_umk,
               'sihalal_perseroan_daerah_id' => $sihalal_nib_perseroan_daerah_id,
               'sihalal_id_pu_induk' => $sihalal_nib_id_pu_induk,
               'sihalal_oss_id' => $sihalal_nib_oss_id,
               'sihalal_modal_dasar' => $sihalal_nib_modal_dasar,
               'sihalal_id_proyek' => $sihalal_nib_id_proyek

            ]);

                return redirect('halal/sihalal-confirm');
            }else{
                return redirect('halal/sihalal-register2');
            }

        }

    }

    public function confirmHalal(Request $request){

        $user_id = Auth::user()->sihalal_userid;
        $id_proyek = Auth::user()->sihalal_id_proyek;
        $password = "temanQu2022";

        $sihalal = Http::post('http://dev-api.halal.go.id/v1/reg_selfdeclare/_reg',
        [
            'userid' => $user_id,
            'id_proyek' => $id_proyek,
            'kode_fac' => '12212',
            'area_pemasaran' => 'bogor',
            'email_pj' => 'pj@gmail.com',
            'jenis_product' => 'barang',
            'merek_dagang' => 'merk',
            'nama_pj' => 'millendra',
            'no_kontak_pj' => '03489238493',
            'jenis_layanan' => 'personal',
            'lph_id' => '2312',
            'id_lembaga' => '1212',
            'no_permohonan'=> '12',
            'product' => [[
                        'reg_prod_name' => 'dddd',
                        'merek' => 'gulaku',
                        'foto_produk' => null,
                        'bahan' => [[
                                    'reg_nama_bahan' => 'Gula',
                                    'no_sertifikat_halal' => 'tidak ada',
                                    'merek' => 'gulaku',
                                    'produsen' => 'indofood',
                                    'tgl_berlaku_sertifikat' => '-'
                                ]]

            ]]

        ])->body();
        $result_json = json_decode($sihalal, true);
         print_r($result_json);

        // if(isset($result_json['statusCode']) && $result_json['statusCode'] == 201){

        //     $result_id_reg = $result_json['data']['id_reg'];
        //     $result_no_daftar = $result_json['data']['id_reg'];
        //     $result_tgl_daftar = $result_json['data']['id_reg'];
        //     $result_nama_pu = $result_json['data']['id_reg'];
        //     $result_alamat_pu =  $result_json['data']['id_reg'];
        //     $result_kota_pu = $result_json['data']['id_reg'];
        //     $result_jenis_usaha = $result_json['data']['id_reg'];
        //     $result_email =  $result_json['data']['id_reg'];
        //     $result_no_telp = $result_json['data']['id_reg'];
        //     $result_jenis_daftar = $result_json['data']['id_reg'];
        //     $result_status_reg = $result_json['data']['id_reg'];
        //     $result_verifikator_id = $result_json['data']['id_reg'];
        //     $result_creator_id = $result_json['data']['id_reg'];
        //     $result_serah_terima_id = $result_json['data']['id_reg'];
        //     $result_skala_usaha = $result_json['data']['id_reg'];
        //     $result_nama_pj =  $result_json['data']['id_reg'];
        //     $result_no_kontak_pj =  $result_json['data']['id_reg'];
        //     $result_email_pj =  $result_json['data']['id_reg'];
        //     $result_alamat_pabrik = $result_json['data']['id_reg'];
        //     $result_status_pabrik = $result_json['data']['id_reg'];
        //     $result_jenis_produk = $result_json['data']['id_reg'];
        //     $result_merek_dagang = $result_json['data']['id_reg'];
        //     $result_area_pemasaran =  $result_json['data']['id_reg'];
        //     $result_tgl_penerimaan_dok = $result_json['data']['id_reg'];
        //     $result_diterima_oleh = $result_json['data']['id_reg'];
        //     $result_no_sp =  $result_json['data']['id_reg'];
        //     $result_tgl_sp = $result_json['data']['id_reg'];
        //     $result_wilayah_id = $result_json['data']['id_reg'];
        //     $result_create_on = $result_json['data']['id_reg'];
        //     $result_create_by = $result_json['data']['id_reg'];
        //     $result_tgl_kirim = $result_json['data']['id_reg'];
        //     $result_kirim_oleh = $result_json['data']['id_reg'];
        //     $result_taken_by = $result_json['data']['id_reg'];
        //     $result_file_sp = $result_json['data']['id_reg'];
        //     $result_no_mohon = $result_json['data']['id_reg'];
        //     $result_tgl_mohon = $result_json['data']['id_reg'];
        //     $result_jenis_layanan = $result_json['data']['id_reg'];
        //     $result_prov_pu = $result_json['data']['id_reg'];
        //     $result_negara_pu = $result_json['data']['id_reg'];
        //     $result_kode_pos_pu =  $result_json['data']['id_reg'];
        //     $result_file_ttd = $result_json['data']['id_reg'];
        //     $result_f_updated = $result_json['data']['id_reg'];
        //     $result_f_updated_by = $result_json['data']['id_reg'];
        //     $result_lph_id = $result_json['data']['id_reg'];
        //     $result_channel_id = $result_json['data']['id_reg'];
        //     $result_fac_id = $result_json['data']['id_reg'];
        //     $result_id_pu =  $result_json['data']['id_reg'];
        //     $result_id_negara =  $result_json['data']['id_reg'];
        //     $result_id_prov = $result_json['data']['id_reg'];
        //     $result_nama_pu_alt = $result_json['data']['id_reg'];
        //     $result_f_apv = $result_json['data']['id_reg'];
        //     $result_ref_no_sert = $result_json['data']['id_reg'];
        //     $result_ref_id_reg = $result_json['data']['id_reg'];
        //     $result_ref_sumber_data = $result_json['data']['id_reg'];
        //     $result_id_unik = $result_json['data']['id_reg'];
        //     $result_f_umk = $result_json['data']['id_reg'];
        //     $result_f_ln = $result_json['data']['id_reg'];
        //     $result_modal_usaha = $result_json['data']['id_reg'];
        //     $result_f_kirim_sh = $result_json['data']['id_reg'];
        //     $result_f_kirm_date = $result_json['data']['id_reg'];
        //     $result_taken_by2 = $result_json['data']['id_reg'];
        //     $result_id_lembaga = $result_json['data']['id_reg'];
        //     $result_terkirim_lnsw = $result_json['data']['id_reg'];
        //     $result_f_lph = $result_json['data']['id_reg'];
        //     $result_f_mui = $result_json['data']['id_reg'];

        $false = false;
        $confirm_success = $this->model->where('sihalal_certified', $false)->update(['sihalal_certified' => true ]);

        //     $halalresult = User::where('email', $mail)
        //     ->update([
        //         'status_sihalal_confirm' => true,
        //         'sihalal_reg_userid' => $userid,
        //         'sihalal_reg_id_reg' => $result_id_reg,
        //         'sihalal_reg_no_daftar' => $result_no_daftar,
        //         'sihalal_reg_tgl_daftar' => $result_tgl_daftar,
        //         'sihalal_reg_nama_pu' => $result_nama_pu,
        //         'sihalal_reg_alamat_pu' => $result_alamat_pu,
        //         'sihalal_reg_kota_pu' => $result_kota_pu,
        //         'sihalal_reg_jenis_usaha' => $result_jenis_usaha,
        //         'sihalal_reg_email' =>  $result_email,
        //         'sihalal_reg_no_telp' => $result_no_telp,
        //         'sihalal_reg_jenis_daftar' => $result_jenis_daftar,
        //         'sihalal_reg_status_reg' => $result_status_reg,
        //         'sihalal_reg_verifikator_id' => $result_verifikator_id,
        //         'sihalal_reg_creator_id' => $result_creator_id,
        //         'sihalal_reg_serah_terima_id' => $result_serah_terima_id,
        //         'sihalal_reg_skala_usaha' => $result_skala_usaha,
        //         'sihalal_reg_nama_pj' =>  $result_nama_pj,
        //         'sihalal_reg_no_kontak_pj' => $result_no_kontak_pj,
        //         'sihalal_reg_email_pj' =>  $result_email_pj,
        //         'sihalal_reg_alamat_pabrik' => $result_alamat_pabrik,
        //         'sihalal_reg_status_pabrik' => $result_status_pabrik,
        //         'sihalal_reg_jenis_produk' => $result_jenis_produk,
        //         'sihalal_reg_merek_dagang' => $result_merek_dagang,
        //         'sihalal_reg_area_pemasaran' => $result_area_pemasaran,
        //         'sihalal_reg_tgl_penerimaan_dok' => $result_tgl_penerimaan_dok,
        //         'sihalal_reg_diterima_oleh' => $result_diterima_oleh,
        //         'sihalal_reg_no_sp' =>  $result_no_sp,
        //         'sihalal_reg_tgl_sp' => $result_tgl_sp,
        //         'sihalal_reg_wilayah_id' => $result_wilayah_id,
        //         'sihalal_reg_create_on' => $result_create_on,
        //         'sihalal_reg_create_by' => $result_create_by,
        //         'sihalal_reg_tgl_kirim' => $result_tgl_kirim,
        //         'sihalal_reg_kirim_oleh' => $result_kirim_oleh,
        //         'sihalal_reg_taken_by' => $result_taken_by,
        //         'sihalal_reg_file_sp' => $result_file_sp,
        //         'sihalal_reg_no_mohon' => $result_no_mohon,
        //         'sihalal_reg_tgl_mohon' => $result_tgl_mohon,
        //         'sihalal_reg_jenis_layanan' => $result_jenis_layanan,
        //         'sihalal_reg_prov_pu' => $result_prov_pu,
        //         'sihalal_reg_negara_pu' => $result_negara_pu,
        //         'sihalal_reg_kode_pos_pu' =>  $result_kode_pos_pu,
        //         'sihalal_reg_file_ttd' =>   $result_file_ttd,
        //         'sihalal_reg_f_updated' => $result_f_updated,
        //         'sihalal_reg_f_updated_by' => $result_f_updated_by,
        //         'sihalal_reg_lph_id' => $result_lph_id,
        //         'sihalal_reg_channel_id' => $result_channel_id,
        //         'sihalal_reg_fac_id' => $result_fac_id,
        //         'sihalal_reg_id_pu' => $result_id_pu,
        //         'sihalal_reg_id_negara' =>  $result_id_negara,
        //         'sihalal_reg_id_prov' => $result_id_prov,
        //         'sihalal_reg_nama_pu_alt' => $result_nama_pu_alt,
        //         'sihalal_reg_f_apv' => $result_f_apv,
        //         'sihalal_reg_ref_no_sert' => $result_ref_no_sert,
        //         'sihalal_reg_ref_id_reg' => $result_ref_id_reg,
        //         'sihalal_reg_ref_sumber_data' => $result_ref_sumber_data,
        //         'sihalal_reg_id_unik' => $result_id_unik,
        //         'sihalal_reg_f_umk' => $result_f_umk,
        //         'sihalal_reg_f_ln' => $result_f_ln,
        //         'sihalal_reg_modal_usaha' => $result_modal_usaha,
        //         'sihalal_reg_f_kirim_sh' => $result_f_kirim_sh,
        //         'sihalal_reg_f_kirm_date' => $result_f_kirm_date,
        //         'sihalal_reg_taken_by2' => $result_taken_by2,
        //         'sihalal_reg_id_lembaga' => $result_id_lembaga,
        //         'sihalal_reg_terkirim_lnsw' => $result_terkirim_lnsw,
        //         'sihalal_reg_f_lph' => $result_f_lph,
        //         'sihalal_reg_f_mui' => $result_f_mui
        //     ] );

        //     return redirect('halal/halal-product');
        // }else{
        //     return redirect('halal/sihalal-confirm');
        // }

    }

}
